import { afterEach, describe, expect, it, vi } from 'vitest'
import { flushPromises, mount } from '@vue/test-utils'
import { createPinia, setActivePinia } from 'pinia'
import ModulesPage from './ModulesPage.vue'
import { useAppStore } from '../app/store'
import { useModuleStore } from '../app/moduleStore'
import { useToastStore } from '../app/toastStore'
import type { ModuleSnapshotItem } from '../contracts/modules'

const item = (overrides: Partial<ModuleSnapshotItem> = {}): ModuleSnapshotItem => ({
  id:'qing.text',displayName:'Text Tools',displayDescription:'Formatting tools',version:'1.0.0',author:'Qing',runtimeType:'OutOfProcess',loadMode:'Manual',runtimeState:'NotLoaded',isValid:true,errorCount:0,errors:[],permissions:[],minimumHostVersion:'0.2',isUserInstalled:true,canLoad:true,canActivate:false,canOpen:false,canDeactivate:false,canUnload:false,isBusy:false,isExecutionBlocked:false,isStartupEnabled:false,startupAuthorizationState:'NotEnabled',canChangeStartupAuthorization:true,isStartupAuthorizationBusy:false,...overrides
})
const mounted: ReturnType<typeof mount>[]=[]
afterEach(()=>{mounted.splice(0).forEach(x=>x.unmount());document.body.innerHTML='';vi.restoreAllMocks()})
function page(module=item(), clientOverrides:Record<string,unknown>={}) {
  const pinia=createPinia();setActivePinia(pinia);useAppStore().bridge='Connected'
  useModuleStore().complete({generatedAt:new Date().toISOString(),modules:[module]})
  const snapshot=()=>({generatedAt:new Date().toISOString(),modules:[module]})
  const client={getSnapshot:vi.fn(async()=>snapshot()),load:vi.fn(async()=>snapshot()),activate:vi.fn(async()=>snapshot()),open:vi.fn(async()=>snapshot()),deactivate:vi.fn(async()=>snapshot()),unload:vi.fn(async()=>snapshot()),setStartupAuthorization:vi.fn(async()=>snapshot()),...clientOverrides}
  const wrapper=mount(ModulesPage,{attachTo:document.body,global:{plugins:[pinia],provide:{moduleClient:client}}});mounted.push(wrapper);return{wrapper,client}
}
describe('ModulesPage lifecycle controls',()=>{
  it('keeps the card a non-interactive container with an independent Details button',()=>{const{wrapper}=page();const card=wrapper.get('.wpf-module-card');expect(card.attributes('role')).toBeUndefined();expect(card.attributes('tabindex')).toBeUndefined();expect(wrapper.get('.module-details-button').element.tagName).toBe('BUTTON')})
  it('Load Enter neither operates nor opens details, while click loads exactly once',async()=>{const{wrapper,client}=page();const load=wrapper.findAll('.module-actions .q-button').find(button=>button.text()==='Load')!;await load.trigger('keydown',{key:'Enter'});expect(client.load).not.toHaveBeenCalled();expect(useModuleStore().selectedModuleId).toBeNull();await load.trigger('click');await flushPromises();expect(client.load).toHaveBeenCalledTimes(1);expect(useModuleStore().selectedModuleId).toBeNull()})
  it('Activate Enter neither operates nor opens details, while click activates exactly once',async()=>{const{wrapper,client}=page(item({runtimeState:'Loaded',canLoad:false,canActivate:true}));const activate=wrapper.findAll('.module-actions .q-button').find(button=>button.text()==='Activate')!;await activate.trigger('keydown',{key:'Enter'});expect(client.activate).not.toHaveBeenCalled();expect(useModuleStore().selectedModuleId).toBeNull();await activate.trigger('click');await flushPromises();expect(client.activate).toHaveBeenCalledTimes(1);expect(useModuleStore().selectedModuleId).toBeNull()})
  it('opens only when authorized without opening Details or optimistic state',async()=>{let resolve!:(value:any)=>void;const pending=new Promise(value=>resolve=value);const module=item({runtimeState:'Loaded',canLoad:false,canOpen:true});const{wrapper,client}=page(module,{open:vi.fn(()=>pending)});const open=wrapper.findAll('.module-actions .q-button').find(button=>button.text()==='Open')!;await open.trigger('click');expect(client.open).toHaveBeenCalledTimes(1);expect(useModuleStore().selectedModuleId).toBeNull();expect(useModuleStore().modules[0].runtimeState).toBe('Loaded');expect(wrapper.text()).toContain('Opening…');resolve({generatedAt:new Date().toISOString(),modules:[module]});await flushPromises();expect(useToastStore().message).toBe('Text Tools window opened or focused.')})
  it('hides Open when the host does not authorize it and shows it in Details when authorized',async()=>{const hidden=page(item({canOpen:false})).wrapper;expect(hidden.findAll('.module-actions .q-button').map(x=>x.text())).not.toContain('Open');hidden.unmount();const{wrapper}=page(item({canLoad:false,canOpen:true,runtimeState:'Loaded'}));await wrapper.get('.module-details-button').trigger('click');expect(wrapper.get('.wpf-module-details').text()).toContain('Open')})
  it('preserves the snapshot and resyncs Open failure at most once',async()=>{const before=item({canLoad:false,canOpen:true,runtimeState:'Loaded'});const getSnapshot=vi.fn().mockRejectedValue(new Error('resync failed'));const{wrapper}=page(before,{open:vi.fn().mockRejectedValue(new Error('ModuleOperationFailed: Open failed.')),getSnapshot});await wrapper.findAll('.module-actions .q-button').find(button=>button.text()==='Open')!.trigger('click');await flushPromises();expect(useModuleStore().modules[0]).toEqual(before);expect(getSnapshot).toHaveBeenCalledTimes(1);expect(useToastStore().message).toContain('ModuleOperationFailed')})
  it.each(['Deactivate','Unload'])('projects %s to both card and details and waits for the host snapshot',async label=>{const operation=label.toLowerCase();let resolve!:(value:any)=>void;const pending=new Promise(value=>resolve=value);const before=item({runtimeState:'Running',canLoad:false,canOpen:true,canDeactivate:true,canUnload:true});const clientOperation=vi.fn(()=>pending);const{wrapper}=page(before,{[operation]:clientOperation});expect(wrapper.findAll('.wpf-module-card .module-actions .q-button').map(button=>button.text())).toContain(label);await wrapper.get('.module-details-button').trigger('click');expect(wrapper.findAll('.wpf-module-details .module-actions .q-button').map(button=>button.text())).toContain(label);await wrapper.findAll('.wpf-module-card .module-actions .q-button').find(button=>button.text()===label)!.trigger('click');expect(useModuleStore().modules[0].runtimeState).toBe('Running');expect(wrapper.text()).toContain(label==='Unload'?'Unloading…':'Deactivating…');resolve({generatedAt:new Date().toISOString(),modules:[item({runtimeState:label==='Unload'?'Unloaded':'Deactivated',canLoad:label==='Unload',canActivate:label!=='Unload',canOpen:label!=='Unload',canDeactivate:false,canUnload:label!=='Unload'})]});await flushPromises();expect(clientOperation).toHaveBeenCalledTimes(1);expect(useModuleStore().modules[0].runtimeState).toBe(label==='Unload'?'Unloaded':'Deactivated');expect(useToastStore().message).toBe(`Text Tools ${label==='Unload'?'unloaded':'deactivated'}.`)})
  it('hides shutdown controls without host capability and after recovery blocking',()=>{const hidden=page(item({canLoad:false})).wrapper;expect(hidden.text()).not.toMatch(/Deactivate|Unload/);hidden.unmount();const blocked=page(item({canLoad:false,canDeactivate:true,canUnload:true,isExecutionBlocked:true})).wrapper;expect(blocked.text()).not.toMatch(/Deactivate|Unload/)})
  it.each([{event:'click',label:'mouse click'},{event:'keydown',options:{key:'Enter'},label:'Enter'},{event:'keydown',options:{key:' '},label:'Space'}])('opens details with $label',async({event,options})=>{const{wrapper}=page();await wrapper.get('.module-details-button').trigger(event,options);expect(useModuleStore().selectedModuleId).toBe('qing.text')})
  it('uses the returned snapshot without optimistic runtime changes',async()=>{let resolve!:(value:any)=>void;const pending=new Promise(value=>resolve=value);const{wrapper}=page(item(),{load:vi.fn(()=>pending)});await wrapper.get('.module-actions .q-button').trigger('click');expect(useModuleStore().modules[0].runtimeState).toBe('NotLoaded');expect(wrapper.text()).toContain('Loading…');resolve({generatedAt:new Date().toISOString(),modules:[item({runtimeState:'Loaded',canLoad:false,canActivate:true})]});await flushPromises();expect(useModuleStore().modules[0].runtimeState).toBe('Loaded');expect(useToastStore().message).toBe('Text Tools loaded.')})
  it('preserves the snapshot, reports the safe error and resyncs at most once',async()=>{const before=item();const getSnapshot=vi.fn().mockRejectedValue(new Error('resync failed'));const{wrapper}=page(before,{load:vi.fn().mockRejectedValue(new Error('ModuleBusy: The requested module is busy.')),getSnapshot});await wrapper.get('.module-actions .q-button').trigger('click');await flushPromises();expect(useModuleStore().modules[0]).toEqual(before);expect(getSnapshot).toHaveBeenCalledTimes(1);expect(useToastStore().message).toContain('ModuleBusy')})
  it('shows recovery blocking and provides the same action in details',async()=>{const blocked=page(item({canLoad:false,isExecutionBlocked:true})).wrapper;expect(blocked.text()).toContain('recovery is pending');expect(blocked.findAll('.module-actions .q-button').map(button=>button.text())).not.toContain('Load');blocked.unmount();const{wrapper}=page(item({canActivate:true,canLoad:false,runtimeState:'Loaded'}));await wrapper.get('.module-details-button').trigger('click');expect(wrapper.get('.wpf-module-details').text()).toContain('Activate')})
  it('closes details with Escape',async()=>{const{wrapper}=page();await wrapper.get('.module-details-button').trigger('click');expect(document.body.textContent).toContain('Minimum host version');window.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape'}));await wrapper.vm.$nextTick();expect(useModuleStore().selectedModuleId).toBeNull()})
  it('keeps startup authorization in details and waits for the host snapshot',async()=>{let resolve!:(value:any)=>void;const pending=new Promise(value=>resolve=value);const before=item();const setStartupAuthorization=vi.fn(()=>pending);const{wrapper}=page(before,{setStartupAuthorization});expect(wrapper.find('.q-switch').exists()).toBe(false);await wrapper.get('.module-details-button').trigger('click');const toggle=wrapper.get('.q-switch');expect(toggle.attributes('role')).toBe('switch');expect(toggle.attributes('aria-checked')).toBe('false');await toggle.trigger('click');expect(setStartupAuthorization).toHaveBeenCalledWith('qing.text',true);expect(useModuleStore().modules[0].isStartupEnabled).toBe(false);expect(wrapper.text()).toContain('Authorizing…');resolve({generatedAt:new Date().toISOString(),modules:[item({isStartupEnabled:true,startupAuthorizationState:'Enabled'})]});await flushPromises();expect(useModuleStore().modules[0].isStartupEnabled).toBe(true);expect(useToastStore().message).toBe('Text Tools will start with QingToolbox.')})
  it('disables an enabled authorization and renders compact card states',async()=>{const enabled=item({isStartupEnabled:true,startupAuthorizationState:'Enabled'});const setStartupAuthorization=vi.fn(async()=>({generatedAt:new Date().toISOString(),modules:[item()]}));const{wrapper}=page(enabled,{setStartupAuthorization});expect(wrapper.get('.wpf-module-card').text()).toContain('Starts on launch');await wrapper.get('.module-details-button').trigger('click');await wrapper.get('.q-switch').trigger('click');await flushPromises();expect(setStartupAuthorization).toHaveBeenCalledWith('qing.text',false);expect(useToastStore().message).toBe('Text Tools will no longer start with QingToolbox.')})
  it('shows changed approval and disables unavailable authorization',async()=>{const changed=page(item({startupAuthorizationState:'ChangedNeedsConfirmation'})).wrapper;expect(changed.get('.wpf-module-card').text()).toContain('Startup approval required');await changed.get('.module-details-button').trigger('click');expect(changed.get('.module-startup-status').text()).toContain('payload changed');changed.unmount();const unavailable=page(item({startupAuthorizationState:'Unavailable',canChangeStartupAuthorization:false})).wrapper;await unavailable.get('.module-details-button').trigger('click');expect(unavailable.get('.q-switch').attributes('disabled')).toBeDefined()})
  it('re-authorizes changed payloads and preserves the old snapshot after failure',async()=>{const before=item({startupAuthorizationState:'ChangedNeedsConfirmation'});const getSnapshot=vi.fn().mockRejectedValue(new Error('resync failed'));const setStartupAuthorization=vi.fn().mockRejectedValue(new Error('ModuleOperationFailed: Authorization failed.'));const{wrapper}=page(before,{getSnapshot,setStartupAuthorization});await wrapper.get('.module-details-button').trigger('click');await wrapper.get('.q-switch').trigger('click');await flushPromises();expect(setStartupAuthorization).toHaveBeenCalledWith('qing.text',true);expect(useModuleStore().modules[0]).toEqual(before);expect(getSnapshot).toHaveBeenCalledTimes(1);expect(useToastStore().message).toContain('ModuleOperationFailed')})
})
