<script setup lang="ts">
import{computed,inject,watch}from'vue'
import type{SettingsClient}from'../bridge/clients/SettingsClient'
import{useAppStore}from'../app/store';import{useSettingsStore}from'../app/settingsStore';import{useThemeStore,type ThemeMode}from'../app/themeStore'
import QPage from'../design-system/components/QPage.vue';import QButton from'../design-system/components/QButton.vue';import QIcon from'../design-system/components/QIcon.vue';import QSkeleton from'../design-system/components/QSkeleton.vue'
const client=inject<SettingsClient>('settingsClient')!;const app=useAppStore();const settings=useSettingsStore();const theme=useThemeStore();const themes:{mode:ThemeMode;label:string}[]=[{mode:'system',label:'Follow system'},{mode:'light',label:'Light'},{mode:'dark',label:'Dark'}]
const refreshed=computed(()=>settings.generatedAt?new Date(settings.generatedAt).toLocaleTimeString():null)
async function refresh(){settings.begin();try{settings.complete(await client.getSnapshot())}catch(error){settings.fail(error)}}
watch(()=>app.bridge,bridge=>{if(bridge==='Connected'&&settings.status==='idle')void refresh()},{immediate:true})
const yesNo=(value:boolean)=>value?'Yes':'No';const enabled=(value:boolean)=>value?'Enabled':'Disabled'
</script>
<template><QPage class="settings-page"><section class="settings-panel"><header class="settings-header"><div><h1>Settings</h1><p>Review the current QingToolbox configuration.</p></div><QButton :disabled="app.bridge!=='Connected'||settings.status==='loading'" @click="refresh"><QIcon name="refresh"/> Refresh</QButton></header><div class="settings-readonly"><QIcon name="statusInfo"/> Settings are read-only in the Development Web workspace.</div><p v-if="settings.status==='ready'&&refreshed" class="settings-refreshed">Last refreshed {{refreshed}}</p>
<section class="settings-group appearance-group"><h2>Appearance</h2><p>This preview applies only to the Development Web workspace.</p><div class="theme-switch settings-theme"><button v-for="item in themes" :key="item.mode" :class="{active:theme.mode===item.mode}" @click="theme.set(item.mode)">{{item.label}}</button></div></section>
<section v-if="app.bridge!=='Connected'&&settings.status==='idle'" class="q-empty settings-state"><div class="q-empty-icon"><QIcon name="settings" :size="28"/></div><h3>Connecting to the host</h3><p>Settings will appear after the host bridge is ready.</p></section>
<section v-else-if="settings.status==='loading'" class="settings-skeleton" aria-label="Loading settings"><QSkeleton v-for="item in 4" :key="item"/></section>
<section v-else-if="settings.status==='error'" class="q-empty settings-state"><div class="q-empty-icon"><QIcon name="statusDanger" :size="28"/></div><h3>Settings are unavailable</h3><p>The current host configuration could not be read.</p><QButton @click="refresh"><QIcon name="refresh"/> Retry</QButton></section>
<template v-else-if="settings.snapshot"><section class="settings-group"><h2>Language</h2><p>The language currently selected by the host.</p><dl class="settings-values"><div><dt>Language</dt><dd>{{settings.snapshot.language.displayName}}</dd></div><div><dt>Language code</dt><dd>{{settings.snapshot.language.code}}</dd></div></dl></section><section class="settings-group"><h2>Logs</h2><p>This reflects the current host navigation preference.</p><dl class="settings-values"><div><dt>Show logs in sidebar</dt><dd><span class="q-badge" :class="settings.snapshot.showLogsInSidebar?'is-success':''">{{enabled(settings.snapshot.showLogsInSidebar)}}</span></dd></div></dl></section><section class="settings-group"><h2>Window closing</h2><dl class="settings-values"><div><dt>Main window close behavior</dt><dd>{{settings.snapshot.mainWindowCloseBehavior}}</dd></div><div v-if="settings.snapshot.closeBehaviorMessage"><dt>Status</dt><dd>{{settings.snapshot.closeBehaviorMessage}}</dd></div></dl></section><section class="settings-group"><h2>Windows startup</h2><dl class="settings-values"><div><dt>Launch at login</dt><dd>{{yesNo(settings.snapshot.launchAtLogin)}}</dd></div><div><dt>Can configure startup</dt><dd>{{yesNo(settings.snapshot.canConfigureLaunchAtLogin)}}</dd></div><div><dt>Startup presentation</dt><dd>{{settings.snapshot.startupPresentationMode}}</dd></div><div><dt>Startup backend</dt><dd>{{settings.snapshot.startupBackend}}</dd></div><div><dt>Startup status</dt><dd>{{settings.snapshot.startupStatus}}</dd></div><div v-if="settings.snapshot.startupMessage"><dt>Message</dt><dd>{{settings.snapshot.startupMessage}}</dd></div></dl></section></template></section></QPage></template>
