import { afterEach, describe, expect, it, vi } from 'vitest'
import { flushPromises, mount, type VueWrapper } from '@vue/test-utils'
import { createPinia, setActivePinia } from 'pinia'
import SettingsPage from './SettingsPage.vue'
import { useAppStore } from '../app/store'
import { useSettingsStore } from '../app/settingsStore'
import { useThemeStore } from '../app/themeStore'
import { useToastStore } from '../app/toastStore'
import { useModuleStore } from '../app/moduleStore'
import type { LanguageCode, SettingsSnapshot } from '../contracts/settings'
import type { ModuleSnapshot } from '../contracts/modules'

const wrappers: VueWrapper[] = []
afterEach(() => wrappers.splice(0).forEach(wrapper => wrapper.unmount()))

const languageOptions = [
  { code: 'system' as const, displayName: 'System Default', nativeName: '跟随系统' },
  { code: 'zh-CN' as const, displayName: 'Simplified Chinese', nativeName: '简体中文' },
  { code: 'en-US' as const, displayName: 'English', nativeName: 'English' },
]
const snapshot: SettingsSnapshot = { generatedAt: '2026-07-25T12:00:00Z', language: { code: 'en-US', effectiveCode: 'en-US', displayName: 'English', options: languageOptions }, showLogsInSidebar: true, mainWindowCloseBehavior: 'Ask', closeBehaviorMessage: 'Ask before closing.', launchAtLogin: false, canConfigureLaunchAtLogin: true, canRepairStartup: false, startupPresentationMode: 'FloatingBadge', startupBackend: 'Registry Run', startupStatus: 'Healthy', startupMessage: 'Registration is healthy.' }
const moduleItem = { id: 'hello', displayName: 'Hello', displayDescription: 'English host metadata', version: '1.0.0', author: 'QingMo', runtimeType: 'InProcess', loadMode: 'Manual', runtimeState: 'NotLoaded', isValid: true, errorCount: 0, errors: [], permissions: [], minimumHostVersion: '0.2.0', isUserInstalled: true, canLoad: true, canActivate: false, canOpen: false, canDeactivate: false, canUnload: false, isBusy: false, isExecutionBlocked: false, isStartupEnabled: false, startupAuthorizationState: 'NotEnabled' as const, canChangeStartupAuthorization: true, isStartupAuthorizationBusy: false }
type PageOptions = {
  bridge?: 'Connecting'|'Connected'|'Unavailable'; status?: 'idle'|'loading'|'ready'|'error'; hasSnapshot?: boolean
  languageImpl?: (value: LanguageCode) => Promise<SettingsSnapshot>
  getImpl?: () => Promise<SettingsSnapshot>; logsImpl?: (value: boolean) => Promise<SettingsSnapshot>
  closeImpl?: (value: 'Ask'|'MinimizeToNotificationArea'|'ExitApplication') => Promise<SettingsSnapshot>
  startupImpl?: (value: 'MainWindow'|'Minimized'|'FloatingBadge') => Promise<SettingsSnapshot>
  launchImpl?: (value: boolean) => Promise<SettingsSnapshot>
  repairImpl?: () => Promise<SettingsSnapshot>
  moduleImpl?: () => Promise<ModuleSnapshot>
}

function page(options: PageOptions = {}) {
  const pinia = createPinia(); setActivePinia(pinia)
  const app = useAppStore(); app.bridge = options.bridge ?? 'Connected'; app.mode = 'Development'
  app.snapshot = { environmentKind: 'Development', environmentDisplayName: 'Development', hostVersion: '0.2.0-alpha', protocolVersion: 4, totalModuleCount: 0, validModuleCount: 0, runningModuleCount: 0, generatedAt: snapshot.generatedAt }
  const settings = useSettingsStore(); const status = options.status ?? 'ready'; const hasSnapshot = options.hasSnapshot ?? status === 'ready'
  if (hasSnapshot) settings.complete(snapshot)
  if (status === 'loading') settings.begin(); else if (status === 'error') settings.fail(new Error('offline')); else settings.status = status
  const getSnapshot = vi.fn(options.getImpl ?? (async () => snapshot))
  const setLanguage = vi.fn(options.languageImpl ?? (async value => ({ ...snapshot, language: { ...snapshot.language, code: value, effectiveCode: value === 'system' ? 'en-US' : value, displayName: languageOptions.find(option => option.code === value)!.displayName } })))
  const setShowLogsInSidebar = vi.fn(options.logsImpl ?? (async value => ({ ...snapshot, showLogsInSidebar: value })))
  const setMainWindowCloseBehavior = vi.fn(options.closeImpl ?? (async value => ({ ...snapshot, mainWindowCloseBehavior: value })))
  const setStartupPresentationMode = vi.fn(options.startupImpl ?? (async value => ({ ...snapshot, startupPresentationMode: value })))
  const setLaunchAtLogin = vi.fn(options.launchImpl ?? (async value => ({ ...snapshot, launchAtLogin: value, generatedAt: '2026-07-25T13:00:00Z' })))
  const repairStartupRegistration = vi.fn(options.repairImpl ?? (async () => ({ ...snapshot, launchAtLogin: true, canRepairStartup: false, generatedAt: '2026-07-25T13:00:00Z' })))
  const getModuleSnapshot = vi.fn(options.moduleImpl ?? (async () => ({ generatedAt: '2026-07-25T12:01:00Z', modules: [] })))
  const wrapper = mount(SettingsPage, { global: { plugins: [pinia], provide: { settingsClient: { getSnapshot, setLanguage, setShowLogsInSidebar, setMainWindowCloseBehavior, setStartupPresentationMode, setLaunchAtLogin, repairStartupRegistration }, moduleClient: { getSnapshot: getModuleSnapshot } } } })
  wrappers.push(wrapper)
  return { wrapper, app, settings, modules: useModuleStore(), getSnapshot, getModuleSnapshot, setLanguage, setShowLogsInSidebar, setMainWindowCloseBehavior, setStartupPresentationMode, setLaunchAtLogin, repairStartupRegistration, theme: useThemeStore(), toast: useToastStore() }
}

async function openSection(wrapper: VueWrapper, title: string) {
  const button = wrapper.findAll('.settings-section-nav button').find(item => item.text().includes(title))
  if (!button) throw new Error(`Missing settings section: ${title}`)
  await button.trigger('click')
}

describe('SettingsPage information architecture', () => {
  it('shows General by default', () => expect(page().wrapper.get('#settings-general-title').text()).toBe('General'))
  it('provides exactly four native section buttons', () => { const buttons = page().wrapper.findAll('.settings-section-nav button'); expect(buttons).toHaveLength(4); expect(buttons.map(x => x.element.tagName)).toEqual(['BUTTON','BUTTON','BUTTON','BUTTON']); expect(buttons.map(x => x.text())).toEqual(expect.arrayContaining([expect.stringContaining('General'), expect.stringContaining('Window'), expect.stringContaining('Startup'), expect.stringContaining('About')])) })
  it('marks the active section accessibly', async () => { const x = page(); expect(x.wrapper.findAll('.settings-section-nav button')[0].attributes('aria-current')).toBe('page'); await openSection(x.wrapper, 'About'); expect(x.wrapper.findAll('.settings-section-nav button')[3].attributes('aria-current')).toBe('page') })
  it('does not request a snapshot when switching sections', async () => { const x = page(); await openSection(x.wrapper, 'Window'); await openSection(x.wrapper, 'Startup'); await openSection(x.wrapper, 'About'); expect(x.getSnapshot).not.toHaveBeenCalled() })
  it('shows Appearance, Language, and Navigation in General', () => { const text = page().wrapper.text(); expect(text).toContain('Appearance'); expect(text).toContain('Language'); expect(text).toContain('Navigation'); expect(text).toContain('Show logs in sidebar') })
  it('renders the three host-provided language choices and confirmed selection', () => { const wrapper = page().wrapper; const group=wrapper.get('[aria-label="Language preference"]'); expect(group.findAll('[role="radio"]')).toHaveLength(3); expect(group.text()).toContain('Follow system'); expect(group.text()).toContain('简体中文'); expect(group.text()).toContain('English'); expect(group.findAll('[role="radio"]').map(option=>option.attributes('aria-checked'))).toEqual(['false','false','true']); expect(wrapper.text()).toContain('Effective languageEnglish') })
  it('does not request the already configured language', async()=>{const x=page();await x.wrapper.get('[aria-label="Language preference"]').findAll('[role="radio"]')[2].trigger('click');expect(x.setLanguage).not.toHaveBeenCalled()})
  it('keeps the old language while pending and applies the confirmed snapshot',async()=>{let resolve!:(value:SettingsSnapshot)=>void;const pending=new Promise<SettingsSnapshot>(done=>resolve=done);const x=page({languageImpl:()=>pending});const choices=x.wrapper.get('[aria-label="Language preference"]').findAll('[role="radio"]');await choices[1].trigger('click');expect(x.setLanguage).toHaveBeenCalledWith('zh-CN');expect(x.settings.snapshot?.language.code).toBe('en-US');expect(choices[2].attributes('aria-checked')).toBe('true');expect(x.wrapper.text()).toContain('Saving…');expect(choices.every(option=>option.attributes('disabled')!==undefined)).toBe(true);expect(x.wrapper.get('[role="switch"]').attributes('disabled')).toBeDefined();await x.wrapper.findAll('.settings-theme button')[1].trigger('click');expect(x.theme.mode).toBe('light');await openSection(x.wrapper,'Window');expect(x.wrapper.get('[aria-label="Main window close behavior"]').findAll('button').every(option=>option.attributes('disabled')!==undefined)).toBe(true);await openSection(x.wrapper,'Startup');expect(x.wrapper.get('[aria-label="Startup presentation mode"]').findAll('button').every(option=>option.attributes('disabled')!==undefined)).toBe(true);resolve({...snapshot,language:{...snapshot.language,code:'zh-CN',effectiveCode:'zh-CN',displayName:'Simplified Chinese'}});await flushPromises();expect(x.settings.snapshot?.language.code).toBe('zh-CN');expect(x.getModuleSnapshot).toHaveBeenCalledTimes(1);expect(x.toast.message).toBe('语言偏好已保存。')})
  it('restores the old snapshot and hides language failure details',async()=>{const x=page({languageImpl:async()=>{throw new Error('C:\\private\\settings.json')}});await x.wrapper.get('[aria-label="Language preference"]').findAll('[role="radio"]')[0].trigger('click');await flushPromises();expect(x.settings.snapshot?.language.code).toBe('en-US');expect(x.settings.status).toBe('ready');expect(x.settings.languageError).toBe('The language setting could not be updated.');expect(x.toast.message).toBe('The language setting could not be updated.');expect(x.wrapper.text()).not.toContain('settings.json')})
  it('disables language choices while disconnected and leaves English page copy in UI-5A1',()=>{const x=page({bridge:'Unavailable'});expect(x.wrapper.get('[aria-label="Language preference"]').findAll('[role="radio"]').every(option=>option.attributes('disabled')!==undefined)).toBe(true);expect(x.wrapper.text()).toContain('Choose the language preference saved by the host.');expect(x.wrapper.text()).toContain('Navigation')})
  it('changes Appearance locally without a host request', async () => { const x = page({ bridge: 'Connecting', status: 'idle', hasSnapshot: false }); await x.wrapper.findAll('.settings-theme button')[2].trigger('click'); expect(x.theme.mode).toBe('dark'); expect(x.getSnapshot).not.toHaveBeenCalled(); expect(x.setShowLogsInSidebar).not.toHaveBeenCalled() })
  it('shows three close behavior radios in Window', async () => { const x = page(); await openSection(x.wrapper, 'Window'); expect(x.wrapper.get('[aria-label="Main window close behavior"]').findAll('[role="radio"]')).toHaveLength(3) })
  it('persists close behavior', async () => { const x = page(); await openSection(x.wrapper, 'Window'); await x.wrapper.get('[aria-label="Main window close behavior"]').findAll('[role="radio"]')[2].trigger('click'); await flushPromises(); expect(x.setMainWindowCloseBehavior).toHaveBeenCalledWith('ExitApplication'); expect(x.settings.snapshot?.mainWindowCloseBehavior).toBe('ExitApplication'); expect(x.toast.kind).toBe('success') })
  it('preserves close behavior after failure', async () => { const x = page({ closeImpl: async () => { throw new Error('denied') } }); await openSection(x.wrapper, 'Window'); await x.wrapper.get('[aria-label="Main window close behavior"]').findAll('[role="radio"]')[1].trigger('click'); await flushPromises(); expect(x.settings.snapshot?.mainWindowCloseBehavior).toBe('Ask'); expect(x.wrapper.text()).toContain('close behavior was not changed') })
  it('shows three startup presentation radios', async () => { const x = page(); await openSection(x.wrapper, 'Startup'); expect(x.wrapper.get('[aria-label="Startup presentation mode"]').findAll('[role="radio"]')).toHaveLength(3) })
  it('persists startup presentation', async () => { const x = page(); await openSection(x.wrapper, 'Startup'); await x.wrapper.get('[aria-label="Startup presentation mode"]').findAll('[role="radio"]')[0].trigger('click'); await flushPromises(); expect(x.setStartupPresentationMode).toHaveBeenCalledWith('MainWindow'); expect(x.settings.snapshot?.startupPresentationMode).toBe('MainWindow') })
  it('preserves startup presentation after failure', async () => { const x = page({ startupImpl: async () => { throw new Error('denied') } }); await openSection(x.wrapper, 'Startup'); await x.wrapper.get('[aria-label="Startup presentation mode"]').findAll('[role="radio"]')[0].trigger('click'); await flushPromises(); expect(x.settings.snapshot?.startupPresentationMode).toBe('FloatingBadge'); expect(x.wrapper.text()).toContain('startup presentation preference was not changed') })
  it('shows startup backend and status badge', async () => { const x = page(); await openSection(x.wrapper, 'Startup'); expect(x.wrapper.text()).toContain('Registry Run'); expect(x.wrapper.get('.startup-health-card .q-badge').text()).toBe('Healthy'); expect(x.wrapper.get('.startup-health-card .q-badge').classes()).toContain('is-success') })
  it('refreshes the full snapshot from Refresh status', async () => { const x = page(); await openSection(x.wrapper, 'Startup'); await x.wrapper.get('.startup-health-actions button').trigger('click'); await flushPromises(); expect(x.getSnapshot).toHaveBeenCalledTimes(1) })
  it('shows and enables the host-confirmed launch-at-login switch', async () => { let resolve!:(value:SettingsSnapshot)=>void; const pending=new Promise<SettingsSnapshot>(done=>{resolve=done}); const x = page({launchImpl:()=>pending}); await openSection(x.wrapper, 'Startup'); const control=x.wrapper.get('.windows-startup-card [role="switch"]'); expect(control.attributes('aria-checked')).toBe('false'); await control.trigger('click'); expect(control.attributes('aria-checked')).toBe('false'); expect(x.setLaunchAtLogin).toHaveBeenCalledWith(true); resolve({...snapshot,launchAtLogin:true,generatedAt:'2026-07-25T13:00:00Z'}); await flushPromises(); expect(x.settings.snapshot?.launchAtLogin).toBe(true); expect(x.toast.message).toContain('will start when you sign in') })
  it('disables launch at login when unavailable and shows safe guidance', async () => { const x=page(); x.settings.complete({...snapshot,canConfigureLaunchAtLogin:false}); await openSection(x.wrapper,'Startup'); expect(x.wrapper.get('.windows-startup-card [role="switch"]').attributes('disabled')).toBeDefined(); expect(x.wrapper.text()).toContain('Windows startup registration is not available in this environment.') })
  it('preserves launch state and reports a safe failure', async () => { const x=page({launchImpl:async()=>{throw new Error('HKCU private path')}}); await openSection(x.wrapper,'Startup'); await x.wrapper.get('.windows-startup-card [role="switch"]').trigger('click'); await flushPromises(); expect(x.settings.snapshot?.launchAtLogin).toBe(false); expect(x.toast.message).toBe('The Windows startup setting could not be updated.'); expect(x.wrapper.text()).not.toContain('HKCU') })
  it('shows repair only when the host reports repairable startup health', async()=>{const x=page();x.settings.complete({...snapshot,canRepairStartup:true,startupStatus:'Degraded'});await openSection(x.wrapper,'Startup');expect(x.wrapper.text()).toContain('Repair startup registration');x.settings.complete(snapshot);await flushPromises();expect(x.wrapper.text()).not.toContain('Repair startup registration')})
  it('keeps repair non-optimistic, locks only startup controls, and applies the returned full snapshot',async()=>{let resolve!:(value:SettingsSnapshot)=>void;const pending=new Promise<SettingsSnapshot>(done=>resolve=done);const x=page({repairImpl:()=>pending});x.settings.complete({...snapshot,canRepairStartup:true,startupStatus:'Degraded'});await openSection(x.wrapper,'Startup');const repair=x.wrapper.findAll('.startup-health-actions button').find(button=>button.text().includes('Repair startup'))!;await repair.trigger('click');expect(x.repairStartupRegistration).toHaveBeenCalledTimes(1);expect(x.settings.snapshot?.canRepairStartup).toBe(true);expect(x.settings.snapshot?.launchAtLogin).toBe(false);expect(x.wrapper.text()).toContain('Repairing…');expect(x.wrapper.get('.windows-startup-card [role="switch"]').attributes('disabled')).toBeDefined();expect(x.wrapper.get('[aria-label="Startup presentation mode"]').findAll('button').every(button=>button.attributes('disabled')!==undefined)).toBe(true);await openSection(x.wrapper,'General');expect(x.wrapper.findAll('.settings-theme button').every(button=>button.attributes('disabled')===undefined)).toBe(true);await openSection(x.wrapper,'Window');expect(x.wrapper.findAll('[role="radio"]').every(button=>button.attributes('disabled')===undefined)).toBe(true);resolve({...snapshot,launchAtLogin:true,canRepairStartup:false,startupStatus:'Healthy'});await flushPromises();expect(x.settings.snapshot?.launchAtLogin).toBe(true);expect(x.settings.snapshot?.canRepairStartup).toBe(false);expect(x.toast.message).toBe('Windows startup registration repaired.')})
  it('accepts a repaired cleanup state that remains disabled',async()=>{const x=page({repairImpl:async()=>({...snapshot,launchAtLogin:false,canRepairStartup:false,startupStatus:'Disabled'})});x.settings.complete({...snapshot,launchAtLogin:true,canRepairStartup:true,startupStatus:'CleanupPending'});await openSection(x.wrapper,'Startup');await x.wrapper.findAll('.startup-health-actions button').find(button=>button.text().includes('Repair startup'))!.trigger('click');await flushPromises();expect(x.settings.snapshot).toMatchObject({launchAtLogin:false,canRepairStartup:false,startupStatus:'Disabled'});expect(x.toast.message).toBe('Windows startup registration repaired.')})
  it('preserves startup state and hides sensitive repair failures',async()=>{const x=page({repairImpl:async()=>{throw new Error('HKCU\\private\\path')}});x.settings.complete({...snapshot,canRepairStartup:true,startupStatus:'Degraded'});await openSection(x.wrapper,'Startup');await x.wrapper.findAll('.startup-health-actions button').find(button=>button.text().includes('Repair startup'))!.trigger('click');await flushPromises();expect(x.settings.snapshot?.canRepairStartup).toBe(true);expect(x.toast.message).toBe('The Windows startup registration could not be repaired.');expect(x.wrapper.text()).not.toContain('HKCU')})
  it('shows brand, Preview, host version, environment, and bridge in About', async () => { const x = page(); await openSection(x.wrapper, 'About'); const text = x.wrapper.text(); expect(text).toContain('QingToolbox'); expect(text).toContain('Preview'); expect(text).toContain('0.2.0-alpha'); expect(text).toContain('Development'); expect(text).toContain('Connected'); expect(x.wrapper.find('.settings-about img').exists()).toBe(true) })
  it('keeps About available without a Settings snapshot', async () => { const x = page({ bridge: 'Connecting', status: 'idle', hasSnapshot: false }); await openSection(x.wrapper, 'About'); expect(x.wrapper.text()).toContain('Modular Windows toolbox.'); expect(x.wrapper.text()).toContain('Connecting') })
  it('keeps old content visible while refreshing', () => { const x = page({ status: 'loading', hasSnapshot: true }); expect(x.wrapper.text()).toContain('English'); expect(x.wrapper.text()).toContain('Refreshing host configuration…'); expect(x.wrapper.find('.settings-host-placeholder').exists()).toBe(false) })
  it('keeps old content visible after refresh failure and offers Retry', () => { const x = page({ status: 'error', hasSnapshot: true }); expect(x.wrapper.text()).toContain('English'); expect(x.wrapper.text()).toContain('Settings refresh failed.'); expect(x.wrapper.get('.settings-snapshot-notice button').text()).toBe('Retry') })
  it('retries refresh failure with an old snapshot', async () => { const x = page({ status: 'error', hasSnapshot: true }); await x.wrapper.get('.settings-snapshot-notice button').trigger('click'); await flushPromises(); expect(x.getSnapshot).toHaveBeenCalledTimes(1) })
  it('keeps old content while disconnected', () => { const x = page({ bridge: 'Unavailable', status: 'ready', hasSnapshot: true }); expect(x.wrapper.text()).toContain('English'); expect(x.wrapper.text()).toContain('The host is disconnected. Showing the last available host configuration.') })
  it('disables host writes while disconnected', async () => { const x = page({ bridge: 'Unavailable', status: 'ready', hasSnapshot: true }); expect(x.wrapper.get('[role="switch"]').attributes('disabled')).toBeDefined(); await openSection(x.wrapper, 'Window'); expect(x.wrapper.findAll('[role="radio"]').every(radio => radio.attributes('disabled') !== undefined)).toBe(true); await openSection(x.wrapper, 'Startup'); expect(x.wrapper.findAll('[role="radio"]').every(radio => radio.attributes('disabled') !== undefined)).toBe(true); expect(x.wrapper.get('.startup-health-actions button').attributes('disabled')).toBeDefined() })
  it('keeps Appearance enabled while disconnected', async () => { const x = page({ bridge: 'Unavailable', status: 'ready', hasSnapshot: true }); await x.wrapper.findAll('.settings-theme button')[1].trigger('click'); expect(x.theme.mode).toBe('light') })
  it('shows Waiting for the host without a snapshot', () => { const x = page({ bridge: 'Connecting', status: 'idle', hasSnapshot: false }); expect(x.wrapper.text()).toContain('Waiting for the host'); expect(x.wrapper.text()).not.toContain('English') })
  it('shows skeletons without a snapshot while loading', () => { const x = page({ status: 'loading', hasSnapshot: false }); expect(x.wrapper.findAll('.settings-host-placeholder .q-skeleton')).toHaveLength(2) })
  it('shows a full host error without a snapshot', () => { const x = page({ status: 'error', hasSnapshot: false }); expect(x.wrapper.text()).toContain('Host settings are unavailable'); expect(x.wrapper.text()).not.toContain('English'); expect(x.wrapper.get('.settings-host-placeholder button').text()).toBe('Retry') })
  it('persists the logs switch', async () => { const x = page(); const control = x.wrapper.get('[role="switch"]'); await control.trigger('click'); await flushPromises(); expect(x.setShowLogsInSidebar).toHaveBeenCalledWith(false); expect(x.settings.snapshot?.showLogsInSidebar).toBe(false) })
  it('preserves logs visibility after failure', async () => { const x = page({ logsImpl: async () => { throw new Error('denied') } }); await x.wrapper.get('[role="switch"]').trigger('click'); await flushPromises(); expect(x.settings.snapshot?.showLogsInSidebar).toBe(true); expect(x.wrapper.text()).toContain('preference was not changed') })
  it('does not lock independent host settings while saving logs', async () => { let resolve!: (value: SettingsSnapshot) => void; const pending = new Promise<SettingsSnapshot>(done => { resolve = done }); const x = page({ logsImpl: () => pending }); await x.wrapper.get('[role="switch"]').trigger('click'); expect(x.wrapper.get('[role="switch"]').attributes('disabled')).toBeDefined(); await openSection(x.wrapper, 'Window'); expect(x.wrapper.findAll('[role="radio"]').every(radio => radio.attributes('disabled') === undefined)).toBe(true); resolve({ ...snapshot, showLogsInSidebar: false }); await flushPromises() })
  it('does not expose Save, Apply, or Reset actions', () => expect(page().wrapper.findAll('button').map(button => button.text())).not.toEqual(expect.arrayContaining(['Save','Apply','Reset'])))
  it('uses a stable responsive workspace structure', () => { const wrapper = page().wrapper; expect(wrapper.find('.settings-workspace').exists()).toBe(true); expect(wrapper.find('.settings-section-nav').exists()).toBe(true); expect(wrapper.find('.settings-section-content').exists()).toBe(true) })
  it('localizes all four sections immediately for an effective Chinese locale', async () => { const x=page(); x.settings.complete({...snapshot,language:{...snapshot.language,code:'system',effectiveCode:'zh-CN'}}); await x.wrapper.vm.$nextTick(); expect(x.wrapper.findAll('.settings-section-nav strong').map(item=>item.text())).toEqual(['常规','窗口','启动','关于']); expect(x.wrapper.text()).toContain('外观'); expect(x.wrapper.attributes()).not.toHaveProperty('data-reloaded') })
  it('formats refresh time with the effective locale', async () => { const format=vi.spyOn(Date.prototype,'toLocaleTimeString').mockReturnValue('localized-time'); const x=page(); expect(format).toHaveBeenCalledWith('en-US'); x.settings.complete({...snapshot,language:{...snapshot.language,effectiveCode:'zh-CN'}}); await x.wrapper.vm.$nextTick(); expect(format).toHaveBeenCalledWith('zh-CN'); format.mockRestore() })
  it('keeps host-projected free text unchanged in Chinese', async () => { const x=page(); x.settings.complete({...snapshot,language:{...snapshot.language,effectiveCode:'zh-CN'},closeBehaviorMessage:'HOST CLOSE TEXT',startupBackend:'Registry Run',startupStatus:'Degraded',startupMessage:'HOST STARTUP TEXT'}); await x.wrapper.vm.$nextTick(); await openSection(x.wrapper,'窗口'); expect(x.wrapper.text()).toContain('HOST CLOSE TEXT'); await openSection(x.wrapper,'启动'); expect(x.wrapper.text()).toContain('Registry Run'); expect(x.wrapper.text()).toContain('Degraded'); expect(x.wrapper.text()).toContain('HOST STARTUP TEXT') })
  it('applies one complete localized module snapshot after language confirmation', async () => { const localized={...moduleItem,displayName:'你好模块',displayDescription:'宿主本地化说明'}; const x=page({moduleImpl:async()=>({generatedAt:'2026-07-25T13:00:00Z',modules:[localized]})}); x.modules.complete({generatedAt:'2026-07-25T12:30:00Z',modules:[moduleItem]}); await x.wrapper.get('[aria-label="Language preference"]').findAll('[role="radio"]')[1].trigger('click'); await flushPromises(); expect(x.getModuleSnapshot).toHaveBeenCalledTimes(1); expect(x.modules.modules).toEqual([localized]); expect(x.modules.lastUpdatedAt).toBe('2026-07-25T13:00:00Z'); expect(x.toast.message).toBe('语言偏好已保存。') })
  it('preserves stale module data and confirmed language when localized metadata refresh fails', async () => { const x=page({moduleImpl:async()=>{throw new Error('C:\\private\\module.json')}}); x.modules.complete({generatedAt:'2026-07-25T12:30:00Z',modules:[moduleItem]}); await x.wrapper.get('[aria-label="Language preference"]').findAll('[role="radio"]')[1].trigger('click'); await flushPromises(); expect(x.settings.snapshot?.language.effectiveCode).toBe('zh-CN'); expect(x.getModuleSnapshot).toHaveBeenCalledTimes(1); expect(x.modules.modules).toEqual([moduleItem]); expect(x.modules.lastUpdatedAt).toBe('2026-07-25T12:30:00Z'); expect(x.modules.status).toBe('error'); expect(x.toast.message).toBe('语言偏好已保存，但无法刷新本地化模块信息。'); expect(x.wrapper.text()).not.toContain('module.json') })
  it('does not request module metadata when the language save fails', async () => { const x=page({languageImpl:async()=>{throw new Error('denied')}}); await x.wrapper.get('[aria-label="Language preference"]').findAll('[role="radio"]')[1].trigger('click'); await flushPromises(); expect(x.getModuleSnapshot).not.toHaveBeenCalled(); expect(x.settings.snapshot?.language.effectiveCode).toBe('en-US'); expect(x.toast.message).toBe('The language setting could not be updated.') })
})
