using QingToolbox.Modules.PowerGuard.Models;
using QingToolbox.Modules.PowerGuard.Services;
using QingToolbox.Modules.PowerGuard.State;
using QingToolbox.ModuleLoader;
using QingToolbox.Core.Runtime;
using QingToolbox.Shell.Services;
using QingToolbox.Abstractions.Localization;
using System.Globalization;
using System.Diagnostics;
using System.Net;
using System.Net.Http;
using System.Text;

var root=Path.Combine(Path.GetTempPath(),$"PowerGuard-smoke-{Guid.NewGuid():N}");Directory.CreateDirectory(root);
try
{
 var time=new ManualTimeProvider();var store=new PowerGuardSettingsStore(root);var events=new PowerGuardEventStore(root,time);var probe=new FakeProbe();var power=new FakePower();var warning=new FakeWarning();
 var settings=new PowerGuardSettings{StartupGraceSeconds=0,OfflineConfirmationSeconds=60,ShutdownCountdownSeconds=600,RecoveryConfirmationSeconds=30};settings.Normalize();
 await using var controller=new PowerGuardController(probe,power,store,events,warning,settings,time);
 var start=time.GetUtcNow();controller.StartForTesting(start);Require(controller.Snapshot.State==PowerGuardState.StartupGrace,"Activation must enter startup grace.");
 await controller.ProcessProbeAsync(Offline(time.GetUtcNow()),time.GetUtcNow());Require(controller.Snapshot.State==PowerGuardState.SuspectedOffline,"Offline candidate must be suspected first.");
 time.Advance(TimeSpan.FromSeconds(10));await controller.ProcessProbeAsync(Online(time.GetUtcNow()),time.GetUtcNow());Require(controller.Snapshot.State==PowerGuardState.Recovering,"Brief outage recovery must not start countdown.");
 time.Advance(TimeSpan.FromSeconds(30));await controller.ProcessProbeAsync(Online(time.GetUtcNow()),time.GetUtcNow());Require(controller.Snapshot.State==PowerGuardState.Online,"Stable recovery must return online.");
 time.Advance(TimeSpan.FromSeconds(10));await controller.ProcessProbeAsync(Offline(time.GetUtcNow()),time.GetUtcNow());time.Advance(TimeSpan.FromSeconds(60));await controller.ProcessProbeAsync(Offline(time.GetUtcNow()),time.GetUtcNow());Require(controller.Snapshot.State==PowerGuardState.Countdown&&warning.ShowCount==1,"Confirmed outage must start one countdown.");
 Require(await controller.EnterMonitoringFaultForTestingAsync(),"Synthetic monitoring fault must be accepted.");Require(controller.Snapshot.State==PowerGuardState.MonitoringFault&&controller.Snapshot.RemainingSeconds==0,"Monitoring fault must invalidate the deadline.");Require(warning.CloseCount>0,"Monitoring fault must stop the ticker and close the real warning.");Require(await controller.RecoverMonitoringForTestingAsync()&&controller.Snapshot.State==PowerGuardState.StartupGrace,"Monitoring fault recovery must use a fresh startup grace period.");
 var restarted=time.GetUtcNow();await controller.ProcessProbeAsync(Offline(restarted),restarted);time.Advance(TimeSpan.FromSeconds(60));await controller.ProcessProbeAsync(Offline(time.GetUtcNow()),time.GetUtcNow());
 var extension=await controller.ExtendCountdownAsync();Require(extension==GuardOperationResult.Succeeded&&controller.Snapshot.RemainingSeconds>600,$"Extension must add ten minutes (state={controller.Snapshot.State}, remaining={controller.Snapshot.RemainingSeconds}).");
 await controller.SuppressCurrentOutageAsync();Require(controller.Snapshot.State==PowerGuardState.SuppressedForCurrentOutage&&warning.CloseCount>0,"Cancel must suppress and close warning.");
 var persisted=await store.ReadAsync();Require(persisted.SuppressedUntilConnectivityRestored,"Suppression must persist.");
 var showsAfterSuppress=warning.ShowCount;time.Advance(TimeSpan.FromMinutes(1));await controller.ProcessProbeAsync(Offline(time.GetUtcNow()),time.GetUtcNow());Require(warning.ShowCount==showsAfterSuppress&&power.Count==0,"Suppressed outage must not warn or shut down.");
 time.Advance(TimeSpan.FromMinutes(1));await controller.ProcessProbeAsync(Online(time.GetUtcNow()),time.GetUtcNow());time.Advance(TimeSpan.FromSeconds(30));await controller.ProcessProbeAsync(Online(time.GetUtcNow()),time.GetUtcNow());Require(!controller.Settings.SuppressedUntilConnectivityRestored&&controller.Snapshot.State==PowerGuardState.Online,"Stable recovery must clear suppression and rearm.");
 time.Advance(TimeSpan.FromMinutes(1));await controller.ProcessProbeAsync(Offline(time.GetUtcNow()),time.GetUtcNow());time.Advance(TimeSpan.FromMinutes(1));await controller.ProcessProbeAsync(Offline(time.GetUtcNow()),time.GetUtcNow());
 time.Advance(TimeSpan.FromMinutes(10));probe.Results.Enqueue(Offline(time.GetUtcNow()));await controller.ProcessProbeAsync(Offline(time.GetUtcNow()),time.GetUtcNow());Require(power.Count==1&&controller.Snapshot.State==PowerGuardState.ExecutingShutdown,"Expired offline countdown must request one normal shutdown after a final offline probe.");
 await controller.ProcessProbeAsync(Offline(time.GetUtcNow()),time.GetUtcNow());Require(power.Count==1,"Power action must not repeat.");
 controller.ResumeForTesting(time.GetUtcNow());Require(controller.Snapshot.State==PowerGuardState.StartupGrace,"Resume must restart grace.");
 var beforeTestPower=power.Count;await controller.ShowTestWarningAsync();Require(power.Count==beforeTestPower&&warning.TestShowCount==1,"Test warning must never invoke power action.");

 var machine=new PowerGuardStateMachine();Require(!machine.TryTransition(PowerGuardState.ExecutingShutdown,DateTimeOffset.UtcNow,out _),"Illegal state transitions must be rejected.");Require(machine.State==PowerGuardState.Disabled,"Rejected transition must not mutate state.");
 Require(await controller.SuppressCurrentOutageAsync()==GuardOperationResult.NotAvailable,"Cancel must be rejected outside Countdown.");Require(await controller.RearmAsync()==GuardOperationResult.NotAvailable,"Rearm must be rejected outside Suppressed state.");
 var launcher=new RetryLauncher();var powerService=new PowerActionService(launcher);Require(await powerService.RequestNormalShutdownAsync()==PowerActionResult.Failed,"A failed launch must be reported.");Require(await powerService.RequestNormalShutdownAsync()==PowerActionResult.Started,"A failed launch must remain retriable.");Require(await powerService.RequestNormalShutdownAsync()==PowerActionResult.AlreadyRequested,"A successful request must be latched.");
 await Task.WhenAll(store.UpdateAsync(s=>s.SuppressedUntilConnectivityRestored=true),store.UpdateAsync(s=>s.ShowRecoveryNotification=false));var merged=await store.ReadAsync();Require(merged.SuppressedUntilConnectivityRestored&&!merged.ShowRecoveryNotification,"Concurrent partial settings updates must not overwrite one another.");
 await VerifyDeterministicTimingAsync(root);await VerifyStaleFinalProbeAsync(root);await VerifyStalePresentationAsync(root);await VerifySettingsRollbackAsync(root);await VerifyDisposalRetryAsync(root);await VerifySupervisorRecoveryAsync(root);await VerifyOfflineHttpProbeAsync();

 await File.WriteAllTextAsync(Path.Combine(root,"settings.json"),"{ invalid");var safe=await store.ReadAsync();Require(safe.GuardEnabled&&Directory.GetFiles(root,"settings.corrupt-*.json").Length==1,"Corrupt settings must use defaults and be backed up.");
 Console.WriteLine("PowerGuard smoke test passed: state, suppression, recovery, extension, resume, safe settings and no real power action.");
 store.Dispose();events.Dispose();
}
finally{if(Directory.Exists(root))Directory.Delete(root,true);}

if(args.Length==2&&args[0]=="--package") await VerifyPackageAsync(args[1]);

static ConnectivityProbeResult Online(DateTimeOffset now)=>new(true,true,[new("fake",true,1,"")],now);
static ConnectivityProbeResult Offline(DateTimeOffset now)=>new(false,false,[new("fake",false,1,"Offline")],now);
static void Require(bool value,string message){if(!value)throw new InvalidOperationException(message);}
static async Task VerifyDeterministicTimingAsync(string parent)
{
 var root=Path.Combine(parent,"deterministic-time");Directory.CreateDirectory(root);var time=new ManualTimeProvider();var probe=new FakeProbe();var power=new FakePower();using var store=new PowerGuardSettingsStore(root);using var events=new PowerGuardEventStore(root,time);
 var settings=new PowerGuardSettings{StartupGraceSeconds=120,OfflineConfirmationSeconds=60,ShutdownCountdownSeconds=600,RecoveryConfirmationSeconds=30};await using var controller=new PowerGuardController(probe,power,store,events,new FakeWarning(),settings,time);controller.StartForTesting(time.GetUtcNow());
 time.Advance(TimeSpan.FromSeconds(119));time.AdjustUtc(TimeSpan.FromHours(1));await controller.ProcessProbeAsync(Offline(time.GetUtcNow()),time.GetUtcNow());Require(controller.Snapshot.State==PowerGuardState.StartupGrace,"UTC forward jump must not bypass the 120-second startup grace boundary.");
 time.Advance(TimeSpan.FromSeconds(1));await controller.ProcessProbeAsync(Offline(time.GetUtcNow()),time.GetUtcNow());Require(controller.Snapshot.State==PowerGuardState.SuspectedOffline,"Startup grace must end at exactly 120 monotonic seconds.");
 time.AdjustUtc(TimeSpan.FromHours(-2));time.Advance(TimeSpan.FromSeconds(59));await controller.ProcessProbeAsync(Offline(time.GetUtcNow()),time.GetUtcNow());Require(controller.Snapshot.State==PowerGuardState.SuspectedOffline,"UTC backward jump must not bypass offline confirmation.");
 time.Advance(TimeSpan.FromSeconds(1));await controller.ProcessProbeAsync(Offline(time.GetUtcNow()),time.GetUtcNow());Require(controller.Snapshot.State==PowerGuardState.Countdown&&controller.Snapshot.RemainingSeconds==600,"Offline confirmation and countdown must meet exact monotonic boundaries.");
 var changedSettings=PowerGuardSettingsStore.Clone(controller.Settings);changedSettings.ShutdownCountdownSeconds=60;Require(await controller.SaveSettingsAsync(changedSettings)==GuardOperationResult.Succeeded&&controller.Snapshot.RemainingSeconds==600,"A running countdown must retain its start-time duration snapshot after settings change.");
 time.AdjustUtc(TimeSpan.FromHours(1));time.Advance(TimeSpan.FromSeconds(599));await controller.ProcessProbeAsync(Offline(time.GetUtcNow()),time.GetUtcNow());Require(power.Count==0&&controller.Snapshot.RemainingSeconds==1,"UTC forward jump must not end countdown early.");
 Require(await controller.ExtendCountdownAsync()==GuardOperationResult.Succeeded,"Countdown extension must be accepted.");time.AdjustUtc(TimeSpan.FromHours(-1));time.Advance(TimeSpan.FromSeconds(600));await controller.ProcessProbeAsync(Offline(time.GetUtcNow()),time.GetUtcNow());Require(power.Count==0&&controller.Snapshot.RemainingSeconds==1,"UTC backward jump must not extend countdown; ten-minute extension uses monotonic time.");
 time.Advance(TimeSpan.FromSeconds(1));var finalOffline=Offline(time.GetUtcNow());probe.Results.Enqueue(finalOffline);await controller.ProcessProbeAsync(finalOffline,time.GetUtcNow());Require(power.Count==1,"Power action must execute once at the exact extended monotonic boundary.");
 var recorded=await events.ReadRecentAsync();Require(recorded.Count>0&&recorded[^1].TimestampUtc==time.GetUtcNow(),"Event records must use the adjustable UTC wall clock.");

 var recoveryRoot=Path.Combine(parent,"deterministic-recovery");Directory.CreateDirectory(recoveryRoot);var recoveryTime=new ManualTimeProvider();using var recoveryStore=new PowerGuardSettingsStore(recoveryRoot);using var recoveryEvents=new PowerGuardEventStore(recoveryRoot,recoveryTime);await using var recovery=new PowerGuardController(new FakeProbe(),new FakePower(),recoveryStore,recoveryEvents,new FakeWarning(),new PowerGuardSettings{StartupGraceSeconds=0,OfflineConfirmationSeconds=15,ShutdownCountdownSeconds=60,RecoveryConfirmationSeconds=30},recoveryTime);recovery.StartForTesting(recoveryTime.GetUtcNow());await recovery.ProcessProbeAsync(Offline(recoveryTime.GetUtcNow()),recoveryTime.GetUtcNow());recoveryTime.Advance(TimeSpan.FromSeconds(15));await recovery.ProcessProbeAsync(Offline(recoveryTime.GetUtcNow()),recoveryTime.GetUtcNow());await recovery.ProcessProbeAsync(Online(recoveryTime.GetUtcNow()),recoveryTime.GetUtcNow());recoveryTime.AdjustUtc(TimeSpan.FromHours(3));recoveryTime.Advance(TimeSpan.FromSeconds(29));await recovery.ProcessProbeAsync(Online(recoveryTime.GetUtcNow()),recoveryTime.GetUtcNow());Require(recovery.Snapshot.State==PowerGuardState.Recovering,"Recovery confirmation must not follow UTC jumps.");recoveryTime.Advance(TimeSpan.FromSeconds(1));await recovery.ProcessProbeAsync(Online(recoveryTime.GetUtcNow()),recoveryTime.GetUtcNow());Require(recovery.Snapshot.State==PowerGuardState.Online,"Recovery confirmation must finish at exactly 30 monotonic seconds.");
 Require(recovery.Snapshot.LastProbeUtc is not null&&recovery.Snapshot.LastSuccessfulProbeUtc is not null&&recovery.Snapshot.ConsecutiveProbeFailures==0,"Probe health snapshot fields must be maintained.");var recoveryLog=await recoveryEvents.ReadRecentAsync();var successCount=recoveryLog.Count(x=>x.Type=="ProbeSucceeded");Require(successCount==1&&recoveryLog.Any(x=>x.Type=="ConnectivityRecovered"),$"Probe success events must be throttled without hiding state transitions (successes={successCount}, events={string.Join(',',recoveryLog.Select(x=>x.Type))}).");
 var throttleRoot=Path.Combine(parent,"failure-throttle");Directory.CreateDirectory(throttleRoot);var throttleTime=new ManualTimeProvider();using var throttleStore=new PowerGuardSettingsStore(throttleRoot);using var throttleEvents=new PowerGuardEventStore(throttleRoot,throttleTime);await using var throttle=new PowerGuardController(new FakeProbe(),new FakePower(),throttleStore,throttleEvents,new FakeWarning(),new PowerGuardSettings{StartupGraceSeconds=0,SuppressedUntilConnectivityRestored=true},throttleTime);throttle.StartForTesting(throttleTime.GetUtcNow());for(var i=0;i<3;i++){await throttle.ProcessProbeAsync(Offline(throttleTime.GetUtcNow()),throttleTime.GetUtcNow());throttleTime.Advance(TimeSpan.FromSeconds(10));}var failureLog=await throttleEvents.ReadRecentAsync();Require(failureLog.Count(x=>x.Type=="ProbeFailed")==1,"Repeated identical probe failures must be rate-limited.");
}
static async Task VerifyStaleFinalProbeAsync(string parent)
{
 var root=Path.Combine(parent,"race");Directory.CreateDirectory(root);var time=new ManualTimeProvider();var blocker=new BlockingProbe();var power=new FakePower();var warning=new FakeWarning();using var store=new PowerGuardSettingsStore(root);using var events=new PowerGuardEventStore(root,time);
 var settings=new PowerGuardSettings{StartupGraceSeconds=0,OfflineConfirmationSeconds=15,ShutdownCountdownSeconds=60,RecoveryConfirmationSeconds=5};await using var controller=new PowerGuardController(blocker,power,store,events,warning,settings,time);var now=time.GetUtcNow();controller.StartForTesting(now);
 await controller.ProcessProbeAsync(Offline(now),now);time.Advance(TimeSpan.FromSeconds(15));await controller.ProcessProbeAsync(Offline(time.GetUtcNow()),time.GetUtcNow());Require(controller.Snapshot.State==PowerGuardState.Countdown,"Race test must enter Countdown.");
 time.Advance(TimeSpan.FromSeconds(60));var final=controller.ProcessProbeAsync(Offline(time.GetUtcNow()),time.GetUtcNow());await blocker.Started.Task.WaitAsync(TimeSpan.FromSeconds(2));Require(await controller.SuppressCurrentOutageAsync()==GuardOperationResult.Succeeded,"Countdown cancellation must succeed during final probe.");blocker.Complete(Offline(time.GetUtcNow()));await final;Require(power.Count==0,"A stale final probe must never request shutdown after cancellation.");
}
static async Task VerifyOfflineHttpProbeAsync()
{
 var targets=new[]{new ConnectivityTarget("text",new Uri("https://offline.test/text"),HttpStatusCode.OK,"ok"),new ConnectivityTarget("status",new Uri("https://offline.test/status"),HttpStatusCode.NoContent,null)};
 var handler=new FakeHttpHandler(async(request,token)=>{await Task.Delay(40,token);return request.RequestUri!.AbsolutePath=="/text"?new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent("ok")}:new HttpResponseMessage(HttpStatusCode.NoContent);});using(var probe=new ConnectivityProbeService(handler,targets,TimeSpan.FromSeconds(1))){var result=await probe.ProbeAsync();Require(result.IsOnline&&handler.MaxConcurrent==2,"Probe endpoints must start concurrently without live network access.");}
 using(var probe=new ConnectivityProbeService(new FakeHttpHandler((_,_)=>Task.FromResult(new HttpResponseMessage(HttpStatusCode.Redirect){Headers={Location=new Uri("https://offline.test/other")}})),[targets[0]],TimeSpan.FromSeconds(1))){Require(!(await probe.ProbeAsync()).IsOnline,"Redirects must not be accepted.");}
 using(var probe=new ConnectivityProbeService(new FakeHttpHandler((_,_)=>Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent("wrong")})),[targets[0]],TimeSpan.FromSeconds(1))){Require(!(await probe.ProbeAsync()).IsOnline,"Text probes must require an exact content match.");}
 using(var probe=new ConnectivityProbeService(new FakeHttpHandler((_,_)=>Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK))),[targets[1]],TimeSpan.FromSeconds(1))){Require(!(await probe.ProbeAsync()).IsOnline,"A 204 target must strictly require status 204.");}
 var large=new byte[1025];using(var probe=new ConnectivityProbeService(new FakeHttpHandler((_,_)=>Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=new ByteArrayContent(large)})),[targets[0]],TimeSpan.FromSeconds(1))){Require((await probe.ProbeAsync()).Endpoints[0].FailureCategory=="ResponseTooLarge","Bodies over 1024 bytes must be rejected.");}
 using(var probe=new ConnectivityProbeService(new FakeHttpHandler(async(_,token)=>{await Task.Delay(Timeout.InfiniteTimeSpan,token);return new HttpResponseMessage(HttpStatusCode.OK);}),targets,TimeSpan.FromMilliseconds(80))){var result=await probe.ProbeAsync();Require(result.Endpoints.All(x=>x.FailureCategory=="Timeout"),"Total probe budget must map endpoint cancellation to Timeout.");}
 using(var probe=new ConnectivityProbeService(new FakeHttpHandler(async(request,token)=>{if(request.RequestUri!.AbsolutePath=="/text")return new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent("ok")};await Task.Delay(Timeout.InfiniteTimeSpan,token);return new HttpResponseMessage(HttpStatusCode.NoContent);}),targets,TimeSpan.FromMilliseconds(80))){Require((await probe.ProbeAsync()).IsOnline,"One strict success must keep the aggregate online when the other endpoint times out.");}
 using(var probe=new ConnectivityProbeService(new FakeHttpHandler(async(_,token)=>{await Task.Delay(Timeout.InfiniteTimeSpan,token);return new HttpResponseMessage(HttpStatusCode.OK);}),targets,TimeSpan.FromSeconds(5))){using var cancelled=new CancellationTokenSource(20);try{await probe.ProbeAsync(cancelled.Token);throw new InvalidOperationException("Caller cancellation was swallowed.");}catch(OperationCanceledException)when(cancelled.IsCancellationRequested){}}
}
static async Task VerifySupervisorRecoveryAsync(string parent)
{
 var root=Path.Combine(parent,"supervisor");Directory.CreateDirectory(root);var time=new ManualTimeProvider();var probe=new ThrowOnceProbe();var warning=new FakeWarning();using var store=new PowerGuardSettingsStore(root);using var events=new PowerGuardEventStore(root,time);await using var controller=new PowerGuardController(probe,new FakePower(),store,events,warning,new PowerGuardSettings{StartupGraceSeconds=120},time,faultBackoff:TimeSpan.FromSeconds(10));
 await controller.ActivateAsync();while(controller.Snapshot.State!=PowerGuardState.MonitoringFault||time.PendingTimerCount==0)await Task.Yield();Require(controller.Snapshot.State==PowerGuardState.MonitoringFault&&time.PendingTimerCount>0,"Synthetic fault must schedule its deterministic backoff.");time.Advance(TimeSpan.FromSeconds(10));await probe.SecondStarted.Task;Require(probe.Count>=2,"Monitor must continue probing after one internal fault.");Require(warning.CloseCount>0,"Monitoring fault must close the real warning surface.");var recent=await events.ReadRecentAsync();Require(recent.Any(x=>x.Type=="MonitoringFault")&&recent.Any(x=>x.Type=="MonitoringRecovered"),"Supervisor must record fault and fresh grace recovery.");await controller.DeactivateAsync();Require(controller.Snapshot.State==PowerGuardState.Disabled,"Deactivate must cleanly finish after monitor recovery.");
}
static async Task VerifyStalePresentationAsync(string parent)
{
 var root=Path.Combine(parent,"presentation");Directory.CreateDirectory(root);var time=new ManualTimeProvider();var warning=new BlockingWarning();using var store=new PowerGuardSettingsStore(root);using var events=new PowerGuardEventStore(root,time);await using var controller=new PowerGuardController(new FakeProbe(),new FakePower(),store,events,warning,new PowerGuardSettings{StartupGraceSeconds=0,OfflineConfirmationSeconds=15,ShutdownCountdownSeconds=60,RecoveryConfirmationSeconds=5},time);var now=time.GetUtcNow();controller.StartForTesting(now);await controller.ProcessProbeAsync(Offline(now),now);time.Advance(TimeSpan.FromSeconds(15));var entering=controller.ProcessProbeAsync(Offline(time.GetUtcNow()),time.GetUtcNow());await warning.ShowStarted.Task.WaitAsync(TimeSpan.FromSeconds(2));var cancel=controller.SuppressCurrentOutageAsync();warning.ReleaseShow();await Task.WhenAll(entering,cancel);Require(!warning.Real&&warning.CloseCount>0,"A stale ShowReal effect must close without leaving a warning window.");
 var stopRoot=Path.Combine(parent,"presentation-stop");Directory.CreateDirectory(stopRoot);var stopTime=new ManualTimeProvider();var stopWarning=new BlockingWarning();using var stopStore=new PowerGuardSettingsStore(stopRoot);using var stopEvents=new PowerGuardEventStore(stopRoot,stopTime);await using var stoppingController=new PowerGuardController(new FakeProbe(),new FakePower(),stopStore,stopEvents,stopWarning,new PowerGuardSettings{StartupGraceSeconds=0,OfflineConfirmationSeconds=15,ShutdownCountdownSeconds=60,RecoveryConfirmationSeconds=5},stopTime);var stopNow=stopTime.GetUtcNow();stoppingController.StartForTesting(stopNow);await stoppingController.ProcessProbeAsync(Offline(stopNow),stopNow);stopTime.Advance(TimeSpan.FromSeconds(15));var stopEntering=stoppingController.ProcessProbeAsync(Offline(stopTime.GetUtcNow()),stopTime.GetUtcNow());await stopWarning.ShowStarted.Task.WaitAsync(TimeSpan.FromSeconds(2));var deactivate=stoppingController.DeactivateAsync();stopWarning.ReleaseShow();await Task.WhenAll(stopEntering,deactivate);Require(!stopWarning.Real&&stoppingController.Snapshot.State==PowerGuardState.Disabled,"Deactivate racing ShowReal must leave no warning or ticker.");
}
static async Task VerifySettingsRollbackAsync(string parent)
{
 var atomicRoot=Path.Combine(parent,"atomic");Directory.CreateDirectory(atomicRoot);using(var good=new PowerGuardSettingsStore(atomicRoot)){await good.WriteSnapshotAsync(new PowerGuardSettings{StartupGraceSeconds=42});}using(var failing=new PowerGuardSettingsStore(atomicRoot,new FailingReplacer())){try{await failing.WriteSnapshotAsync(new PowerGuardSettings{StartupGraceSeconds=99});throw new InvalidOperationException("Synthetic replacement failure was ignored.");}catch(IOException){}var intact=await failing.ReadAsync();Require(intact.StartupGraceSeconds==42,"Atomic replacement failure must preserve the old valid settings file.");}
 var suppressRoot=Path.Combine(parent,"suppress-failure");Directory.CreateDirectory(suppressRoot);var suppressTime=new ManualTimeProvider();var warning=new FakeWarning();using var suppressStore=new PowerGuardSettingsStore(suppressRoot,new FailingReplacer());using var suppressEvents=new PowerGuardEventStore(suppressRoot,suppressTime);await using(var controller=new PowerGuardController(new FakeProbe(),new FakePower(),suppressStore,suppressEvents,warning,new PowerGuardSettings{StartupGraceSeconds=0,OfflineConfirmationSeconds=15,ShutdownCountdownSeconds=60,RecoveryConfirmationSeconds=5},suppressTime)){var now=suppressTime.GetUtcNow();controller.StartForTesting(now);await controller.ProcessProbeAsync(Offline(now),now);suppressTime.Advance(TimeSpan.FromSeconds(15));await controller.ProcessProbeAsync(Offline(suppressTime.GetUtcNow()),suppressTime.GetUtcNow());Require(await controller.SuppressCurrentOutageAsync()==GuardOperationResult.Failed&&controller.Snapshot.State==PowerGuardState.Countdown&&warning.Real,"Failed suppression persistence must retain the original countdown presentation.");}
 var rearmRoot=Path.Combine(parent,"rearm-failure");Directory.CreateDirectory(rearmRoot);using var rearmStore=new PowerGuardSettingsStore(rearmRoot,new FailingReplacer());using var rearmEvents=new PowerGuardEventStore(rearmRoot);await using(var controller=new PowerGuardController(new FakeProbe(),new FakePower(),rearmStore,rearmEvents,new FakeWarning(),new PowerGuardSettings{SuppressedUntilConnectivityRestored=true,StartupGraceSeconds=0})){var now=DateTimeOffset.UtcNow;controller.StartForTesting(now);await controller.ProcessProbeAsync(Offline(now),now);Require(controller.Snapshot.State==PowerGuardState.SuppressedForCurrentOutage,"Rearm rollback test must begin suppressed.");Require(await controller.RearmAsync()==GuardOperationResult.Failed&&controller.Snapshot.State==PowerGuardState.SuppressedForCurrentOutage,"Failed rearm persistence must retain the suppressed state.");}
}
static async Task VerifyDisposalRetryAsync(string parent)
{
 var root=Path.Combine(parent,"dispose-retry");Directory.CreateDirectory(root);var time=new ManualTimeProvider();var probe=new HangingProbe();using var store=new PowerGuardSettingsStore(root);using var events=new PowerGuardEventStore(root,time);var controller=new PowerGuardController(probe,new FakePower(),store,events,new FakeWarning(),new PowerGuardSettings(),time,cleanupTimeout:TimeSpan.FromSeconds(15));await controller.ActivateAsync();await probe.Started.Task.WaitAsync(TimeSpan.FromSeconds(2));var disposing=controller.DisposeAsync().AsTask();for(var i=0;i<100&&time.PendingTimerCount==0;i++)await Task.Yield();Require(time.PendingTimerCount>0,"Dispose must schedule its deterministic cleanup timeout.");time.Advance(TimeSpan.FromSeconds(15));try{await disposing;throw new InvalidOperationException("Unsafe disposal unexpectedly succeeded while the monitor was alive.");}catch(PowerGuardCleanupException){}Require(await controller.SuppressCurrentOutageAsync()==GuardOperationResult.NotAvailable,"Failed disposal must retain usable synchronization resources.");probe.Release();await controller.DisposeAsync();
}
static async Task VerifyPackageAsync(string package)
{
 var root=Path.Combine(Path.GetTempPath(),$"PowerGuard-import-{Guid.NewGuid():N}");var modules=Path.Combine(root,"Modules");var data=Path.Combine(root,"Data");
 try
 {
  var reader=new ModuleManifestReader();var validator=new ModuleManifestValidator();var importer=new ModulePackageImporter(reader,validator);
  var id=await importer.ImportAsync(package,modules);Require(id=="qing.powerguard","Imported package id is incorrect.");
  var discovered=await new ModuleManifestScanner(reader,validator).ScanAsync(modules);Require(discovered.Count==1&&discovered[0].IsValid,"Latest host could not discover imported PowerGuard.");
  Directory.CreateDirectory(Path.Combine(data,id));await File.WriteAllTextAsync(Path.Combine(data,id,"settings.json"),"{\"GuardEnabled\":false}");
  await RunImportedLifecycleAsync(discovered,id,data);
  Console.WriteLine("Latest toolbox import/load/activate/deactivate/unload integration passed.");
 }
 finally
 {
  for(var i=0;i<3;i++){GC.Collect();GC.WaitForPendingFinalizers();await Task.Delay(50);}
  try{if(Directory.Exists(root))Directory.Delete(root,true);}catch(UnauthorizedAccessException){Console.WriteLine("Imported module files remain temporarily locked; OS temp cleanup will remove the isolated directory.");}
 }
}
static async Task RunImportedLifecycleAsync(IReadOnlyList<QingToolbox.Abstractions.Modules.DiscoveredModule> discovered,string id,string data)
{
 await using var runtime=new ModuleRuntimeManager(new InProcessModuleLoader(new FakeLocalization()));runtime.ReplaceDiscoveredModules(discovered);
 Require(runtime.GetRecord(id)?.State==QingToolbox.Abstractions.Modules.ModuleState.NotLoaded,"Import must remain NotLoaded.");
 await runtime.LoadAsync(id,data);Require(runtime.GetRecord(id)?.IsLoaded==true,"Latest host failed to load PowerGuard.");
 await runtime.ActivateAsync(id);await runtime.DeactivateAsync(id);await runtime.UnloadAsync(id);
}
sealed class FakeProbe:IConnectivityProbe{public Queue<ConnectivityProbeResult> Results{get;}=[];public Task<ConnectivityProbeResult> ProbeAsync(CancellationToken token=default)=>Task.FromResult(Results.Count>0?Results.Dequeue():new ConnectivityProbeResult(false,false,[new("fake",false,1,"Offline")],DateTimeOffset.UtcNow));}
sealed class BlockingProbe:IConnectivityProbe{public TaskCompletionSource Started{get;}=new(TaskCreationOptions.RunContinuationsAsynchronously);private readonly TaskCompletionSource<ConnectivityProbeResult> _result=new(TaskCreationOptions.RunContinuationsAsynchronously);public async Task<ConnectivityProbeResult> ProbeAsync(CancellationToken token=default){Started.TrySetResult();return await _result.Task.WaitAsync(token);}public void Complete(ConnectivityProbeResult result)=>_result.TrySetResult(result);}
sealed class ThrowOnceProbe:IConnectivityProbe{public int Count;public TaskCompletionSource SecondStarted{get;}=new(TaskCreationOptions.RunContinuationsAsynchronously);public Task<ConnectivityProbeResult> ProbeAsync(CancellationToken token=default){var count=Interlocked.Increment(ref Count);if(count==1)throw new InvalidOperationException("safe synthetic monitor fault");SecondStarted.TrySetResult();return Task.FromResult(new ConnectivityProbeResult(true,true,[new("fake",true,1,"")],DateTimeOffset.UtcNow));}}
sealed class HangingProbe:IConnectivityProbe{public TaskCompletionSource Started{get;}=new(TaskCreationOptions.RunContinuationsAsynchronously);private readonly TaskCompletionSource _release=new(TaskCreationOptions.RunContinuationsAsynchronously);public async Task<ConnectivityProbeResult> ProbeAsync(CancellationToken token=default){Started.TrySetResult();await _release.Task;return new ConnectivityProbeResult(true,true,[new("fake",true,1,"")],DateTimeOffset.UtcNow);}public void Release()=>_release.TrySetResult();}
sealed class FakeHttpHandler(Func<HttpRequestMessage,CancellationToken,Task<HttpResponseMessage>> response):HttpMessageHandler{private int _active,_max;public int MaxConcurrent=>_max;protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,CancellationToken token){var active=Interlocked.Increment(ref _active);int current;while(active>(current=_max))Interlocked.CompareExchange(ref _max,active,current);try{return await response(request,token);}finally{Interlocked.Decrement(ref _active);}}}
sealed class FailingReplacer:IAtomicFileReplacer{public void Replace(string temporaryPath,string destinationPath)=>throw new IOException("safe synthetic replace failure");}
sealed class BlockingWarning:IWarningPresenter{public TaskCompletionSource ShowStarted{get;}=new(TaskCreationOptions.RunContinuationsAsynchronously);private readonly TaskCompletionSource _release=new(TaskCreationOptions.RunContinuationsAsynchronously);public bool Real;public int CloseCount;public async Task ShowRealAsync(int seconds,CancellationToken token=default){ShowStarted.TrySetResult();await _release.Task;Real=true;}public void ReleaseShow()=>_release.TrySetResult();public Task<TestPreviewResult> ShowTestAsync(int seconds,CancellationToken token=default)=>Task.FromResult(TestPreviewResult.UnavailableDuringCountdown);public Task UpdateRealAsync(int seconds,CancellationToken token=default)=>Task.CompletedTask;public Task CloseRealAsync(CancellationToken token=default){Real=false;CloseCount++;return Task.CompletedTask;}public Task CloseTestAsync(CancellationToken token=default)=>Task.CompletedTask;public Task CloseAllAsync(CancellationToken token=default)=>CloseRealAsync(token);}
sealed class FakePower:IPowerActionService{public int Count;public PowerActionResult Result=PowerActionResult.Started;public Task<PowerActionResult> RequestNormalShutdownAsync(CancellationToken token=default){Count++;return Task.FromResult(Result);}}
sealed class RetryLauncher:IProcessLauncher{private int _count;public Process? Start(ProcessStartInfo info)=>Interlocked.Increment(ref _count)==1?null:Process.GetCurrentProcess();}
sealed class FakeWarning:IWarningPresenter{public int ShowCount,TestShowCount,CloseCount,UpdateCount;public bool Real;public Task ShowRealAsync(int seconds,CancellationToken token=default){Real=true;ShowCount++;return Task.CompletedTask;}public Task<TestPreviewResult> ShowTestAsync(int seconds,CancellationToken token=default){if(Real)return Task.FromResult(TestPreviewResult.UnavailableDuringCountdown);TestShowCount++;return Task.FromResult(TestPreviewResult.Opened);}public Task UpdateRealAsync(int seconds,CancellationToken token=default){UpdateCount++;return Task.CompletedTask;}public Task CloseRealAsync(CancellationToken token=default){Real=false;CloseCount++;return Task.CompletedTask;}public Task CloseTestAsync(CancellationToken token=default)=>Task.CompletedTask;public Task CloseAllAsync(CancellationToken token=default){Real=false;CloseCount++;return Task.CompletedTask;}}
sealed class FakeLocalization:ILocalizationService{public CultureInfo CurrentCulture=>CultureInfo.InvariantCulture;public string CurrentLanguageCode=>"en-US";public event EventHandler? CultureChanged { add { } remove { } } public string GetString(string key)=>key;public string GetString(string key,params object[] args)=>string.Format(CultureInfo.InvariantCulture,key,args);public string GetModuleString(string moduleId,string key,string? fallback=null)=>fallback??key;public string GetModuleString(string moduleId,string key,string? fallback,params object[] args)=>string.Format(CultureInfo.InvariantCulture,fallback??key,args);}
