import { describe, expect, it } from 'vitest'
import { MockTransport } from '../transport/MockTransport'
import { RequestClient } from './RequestClient'
import { EventDispatcher } from './EventDispatcher'
import { isAppSnapshot, isPingResponse, isReadyChallenge, protocolVersion } from '../../contracts/app'
import { createPinia, setActivePinia } from 'pinia'
import { useAppStore } from '../../app/store'
import { WebViewTransport } from '../transport/WebViewTransport'
import { UnavailableTransport } from '../transport/UnavailableTransport'
import { AppClient } from '../clients/AppClient'

describe('Qing Bridge frontend', () => {
  it('requires activation before a snapshot', async()=>{await expect(new RequestClient(new MockTransport()).request('app.getSnapshot')).rejects.toThrow('BridgeNotActivated')})
  it('models explicit module load and activation with authoritative snapshots',async()=>{const transport=new MockTransport();const requests=new RequestClient(transport);await expect(requests.request('modules.load',{moduleId:'qing.hello'})).rejects.toThrow('BridgeNotActivated');const app=new AppClient(requests);await app.ready('Mock');await app.ping();for(const payload of [{},{moduleId:1},{moduleId:''},{moduleId:'qing.hello',extra:true}])await expect(requests.request('modules.load',payload)).rejects.toThrow('InvalidPayload');await expect(requests.request('modules.load',{moduleId:'QING.HELLO'})).rejects.toThrow('ModuleNotFound');const loaded=await requests.request<any>('modules.load',{moduleId:'qing.hello'});expect(loaded.modules[0]).toMatchObject({runtimeState:'Loaded',canLoad:false,canActivate:true});const activated=await requests.request<any>('modules.activate',{moduleId:'qing.hello'});expect(activated.modules[0]).toMatchObject({runtimeState:'Running',canActivate:false});const refreshed=await requests.request<any>('modules.getSnapshot');expect(refreshed.modules[0].runtimeState).toBe('Running');await expect(requests.request('modules.activate',{moduleId:'qing.hello'})).rejects.toThrow('ModuleOperationUnavailable')})
  it('models host-confirmed module open without changing runtime state',async()=>{const transport=new MockTransport();const requests=new RequestClient(transport);const app=new AppClient(requests);await app.ready('Mock');await app.ping();for(const payload of [{},{moduleId:1},{moduleId:'qing.texttools',extra:true}])await expect(requests.request('modules.open',payload)).rejects.toThrow('InvalidPayload');await expect(requests.request('modules.open',{moduleId:'QING.TEXTTOOLS'})).rejects.toThrow('ModuleNotFound');const opened=await requests.request<any>('modules.open',{moduleId:'qing.texttools'});expect(opened.modules[1]).toMatchObject({runtimeState:'Running',canOpen:true});await expect(requests.request('modules.open',{moduleId:'qing.hello'})).rejects.toThrow('ModuleOperationUnavailable')})
  it('models explicit module deactivation and unload with authoritative snapshots',async()=>{const transport=new MockTransport();const requests=new RequestClient(transport);await expect(requests.request('modules.deactivate',{moduleId:'qing.texttools'})).rejects.toThrow('BridgeNotActivated');const app=new AppClient(requests);await app.ready('Mock');await app.ping();for(const command of ['modules.deactivate','modules.unload'])for(const payload of [{},{moduleId:1},{moduleId:''},{moduleId:'qing.texttools',extra:true}])await expect(requests.request(command,payload)).rejects.toThrow('InvalidPayload');await expect(requests.request('modules.unload',{moduleId:'QING.TEXTTOOLS'})).rejects.toThrow('ModuleNotFound');const deactivated=await requests.request<any>('modules.deactivate',{moduleId:'qing.texttools'});expect(deactivated.modules[1]).toMatchObject({runtimeState:'Deactivated',canActivate:true,canDeactivate:false,canUnload:true});const unloaded=await requests.request<any>('modules.unload',{moduleId:'qing.texttools'});expect(unloaded.modules[1]).toMatchObject({runtimeState:'Unloaded',canLoad:true,canDeactivate:false,canUnload:false});const refreshed=await requests.request<any>('modules.getSnapshot');expect(refreshed.modules[1]).toMatchObject({runtimeState:'Unloaded',canLoad:true});await expect(requests.request('modules.unload',{moduleId:'qing.texttools'})).rejects.toThrow('ModuleOperationUnavailable')})
  it('models startup authorization without changing runtime state',async()=>{const requests=new RequestClient(new MockTransport());await expect(requests.request('modules.setStartupAuthorization',{moduleId:'qing.hello',enabled:true})).rejects.toThrow('BridgeNotActivated');const app=new AppClient(requests);await app.ready('Mock');await app.ping();for(const payload of [{},{moduleId:'qing.hello'},{moduleId:1,enabled:true},{moduleId:'qing.hello',enabled:'true'},{moduleId:'qing.hello',enabled:true,extra:true}])await expect(requests.request('modules.setStartupAuthorization',payload)).rejects.toThrow('InvalidPayload');await expect(requests.request('modules.setStartupAuthorization',{moduleId:'QING.HELLO',enabled:true})).rejects.toThrow('ModuleNotFound');const enabled=await requests.request<any>('modules.setStartupAuthorization',{moduleId:'qing.hello',enabled:true});expect(enabled.modules[0]).toMatchObject({runtimeState:'NotLoaded',isStartupEnabled:true,startupAuthorizationState:'Enabled'});const disabled=await requests.request<any>('modules.setStartupAuthorization',{moduleId:'qing.hello',enabled:false});expect(disabled.modules[0]).toMatchObject({runtimeState:'NotLoaded',isStartupEnabled:false,startupAuthorizationState:'NotEnabled'});const refreshed=await requests.request<any>('modules.getSnapshot');expect(refreshed.modules[0].startupAuthorizationState).toBe('NotEnabled')})
  it('gates the deterministic settings snapshot and rejects non-empty payloads',async()=>{const transport=new MockTransport();const requests=new RequestClient(transport);await expect(requests.request('settings.getSnapshot')).rejects.toThrow('BridgeNotActivated');const app=new AppClient(requests);await app.ready('Mock');await app.ping();await expect(requests.request('settings.getSnapshot',{save:true})).rejects.toThrow('InvalidPayload');const snapshot=await requests.request<{showLogsInSidebar:boolean}>('settings.getSnapshot');expect(snapshot.showLogsInSidebar).toBe(true)})
  it('validates and persists the logs navigation preference in Mock',async()=>{const transport=new MockTransport();const requests=new RequestClient(transport);await expect(requests.request('settings.setShowLogsInSidebar',{showLogsInSidebar:false})).rejects.toThrow('BridgeNotActivated');const app=new AppClient(requests);await app.ready('Mock');await app.ping();for(const payload of [{},{showLogsInSidebar:'false'},{showLogsInSidebar:false,extra:true}])await expect(requests.request('settings.setShowLogsInSidebar',payload)).rejects.toThrow('InvalidPayload');const changed=await requests.request<{showLogsInSidebar:boolean}>('settings.setShowLogsInSidebar',{showLogsInSidebar:false});expect(changed.showLogsInSidebar).toBe(false);const refreshed=await requests.request<{showLogsInSidebar:boolean}>('settings.getSnapshot');expect(refreshed.showLogsInSidebar).toBe(false)})
  it('validates and persists the close behavior in Mock without changing logs',async()=>{const transport=new MockTransport();const requests=new RequestClient(transport);await expect(requests.request('settings.setMainWindowCloseBehavior',{mainWindowCloseBehavior:'Ask'})).rejects.toThrow('BridgeNotActivated');const app=new AppClient(requests);await app.ready('Mock');await app.ping();for(const payload of [{},{mainWindowCloseBehavior:1},{mainWindowCloseBehavior:'ask'},{mainWindowCloseBehavior:'Unknown'},{mainWindowCloseBehavior:'Ask',extra:true}])await expect(requests.request('settings.setMainWindowCloseBehavior',payload)).rejects.toThrow('InvalidPayload');const changed=await requests.request<{mainWindowCloseBehavior:string;showLogsInSidebar:boolean}>('settings.setMainWindowCloseBehavior',{mainWindowCloseBehavior:'ExitApplication'});expect(changed.mainWindowCloseBehavior).toBe('ExitApplication');expect(changed.showLogsInSidebar).toBe(true);const refreshed=await requests.request<{mainWindowCloseBehavior:string}>('settings.getSnapshot');expect(refreshed.mainWindowCloseBehavior).toBe('ExitApplication')})
  it('validates and persists startup presentation in Mock without changing other settings',async()=>{const transport=new MockTransport();const requests=new RequestClient(transport);await expect(requests.request('settings.setStartupPresentationMode',{startupPresentationMode:'MainWindow'})).rejects.toThrow('BridgeNotActivated');const app=new AppClient(requests);await app.ready('Mock');await app.ping();for(const payload of [{},{startupPresentationMode:1},{startupPresentationMode:''},{startupPresentationMode:'floatingbadge'},{startupPresentationMode:'Unknown'},{startupPresentationMode:'MainWindow',extra:true}])await expect(requests.request('settings.setStartupPresentationMode',payload)).rejects.toThrow('InvalidPayload');const changed=await requests.request<{startupPresentationMode:string;showLogsInSidebar:boolean;mainWindowCloseBehavior:string;launchAtLogin:boolean}>('settings.setStartupPresentationMode',{startupPresentationMode:'Minimized'});expect(changed).toMatchObject({startupPresentationMode:'Minimized',showLogsInSidebar:true,mainWindowCloseBehavior:'MinimizeToNotificationArea',launchAtLogin:false});const refreshed=await requests.request<{startupPresentationMode:string}>('settings.getSnapshot');expect(refreshed.startupPresentationMode).toBe('Minimized')})
  it('validates and persists Launch at login in Mock',async()=>{const transport=new MockTransport();const requests=new RequestClient(transport);await expect(requests.request('settings.setLaunchAtLogin',{enabled:true})).rejects.toThrow('BridgeNotActivated');const app=new AppClient(requests);await app.ready('Mock');await app.ping();for(const payload of [{},{enabled:'true'},{enabled:true,extra:true}])await expect(requests.request('settings.setLaunchAtLogin',payload)).rejects.toThrow('InvalidPayload');const changed=await requests.request<{launchAtLogin:boolean;startupPresentationMode:string}>('settings.setLaunchAtLogin',{enabled:true});expect(changed.launchAtLogin).toBe(true);expect(changed.startupPresentationMode).toBe('FloatingBadge');const refreshed=await requests.request<{launchAtLogin:boolean}>('settings.getSnapshot');expect(refreshed.launchAtLogin).toBe(true);transport.canConfigureLaunchAtLogin=false;await expect(requests.request('settings.setLaunchAtLogin',{enabled:false})).rejects.toThrow('SettingsMutationUnavailable')})
  it('requires activation and an empty payload for startup repair and persists host-confirmed state',async()=>{const transport=new MockTransport();const requests=new RequestClient(transport);await expect(requests.request('settings.repairStartupRegistration',{})).rejects.toThrow('BridgeNotActivated');const app=new AppClient(requests);await app.ready('Mock');await app.ping();await expect(requests.request('settings.repairStartupRegistration',{extra:true})).rejects.toThrow('InvalidPayload');const changed=await requests.request<{canRepairStartup:boolean;launchAtLogin:boolean}>('settings.repairStartupRegistration',{});expect(changed).toMatchObject({canRepairStartup:false,launchAtLogin:true});expect(await requests.request('settings.getSnapshot')).toMatchObject({canRepairStartup:false});await expect(requests.request('settings.repairStartupRegistration',{})).rejects.toThrow('SettingsMutationUnavailable');for(const command of ['settings.testStartup','settings.openTaskScheduler'])await expect(requests.request(command,{})).rejects.toThrow('UnknownCommand')})
  it('activates once and supports second and third session pings',async()=>{const client=new AppClient(new RequestClient(new MockTransport()));expect((await client.ready('Mock')).environmentKind).toBe('Mock');expect((await client.ping()).sessionToken).toBeTruthy();expect((await client.ping()).sessionToken).toBeUndefined();expect((await client.ping()).pong).toBe(true);expect((await client.getSnapshot()).environmentKind).toBe('Mock')})
  it('rejects a replayed activation nonce',async()=>{const transport=new MockTransport();const requests=new RequestClient(transport);const ready=await requests.request<{activationNonce:string}>('web.ready',{assetBuildId:'x',documentReadyState:'complete',transportMode:'Mock'});await requests.request('app.ping',{activationNonce:ready.activationNonce});await expect(requests.request('app.ping',{activationNonce:ready.activationNonce})).rejects.toThrow('InvalidActivationNonce')})
  it('rejects wrong and ambiguous session credentials',async()=>{const transport=new MockTransport();const requests=new RequestClient(transport);const ready=await requests.request<{activationNonce:string}>('web.ready',{});await requests.request('app.ping',{activationNonce:ready.activationNonce});await expect(requests.request('app.ping',{sessionToken:'wrong'})).rejects.toThrow('InvalidSessionToken');await expect(requests.request('app.ping',{activationNonce:'x',sessionToken:'y'})).rejects.toThrow('InvalidPingCredential')})
  it('disposes every activation credential',async()=>{const client=new AppClient(new RequestClient(new MockTransport()));await client.ready('Mock');await client.ping();client.dispose();await expect(client.ping()).rejects.toThrow('unavailable')})
  it('does not reuse a token after reload',async()=>{const first=new MockTransport();const requests=new RequestClient(first);const ready=await requests.request<{activationNonce:string}>('web.ready',{});const activated=await requests.request<{sessionToken:string}>('app.ping',{activationNonce:ready.activationNonce});first.dispose();const reloaded=new RequestClient(new MockTransport());await expect(reloaded.request('app.ping',{sessionToken:activated.sessionToken})).rejects.toThrow('BridgeNotActivated')})
  it('validates challenges snapshots session tokens and ping responses',()=>{const snapshot={environmentKind:'Development',environmentDisplayName:'Development',hostVersion:'1',protocolVersion,totalModuleCount:1,validModuleCount:1,runningModuleCount:0,generatedAt:new Date().toISOString()};expect(isAppSnapshot(snapshot)).toBe(true);expect(isReadyChallenge({activationNonce:'a'.repeat(64),snapshot})).toBe(true);expect(isPingResponse({pong:true,hostTime:new Date().toISOString(),sessionToken:'b'.repeat(64),activated:true})).toBe(true);expect(isPingResponse({pong:true,hostTime:new Date().toISOString(),sessionToken:'short',activated:true})).toBe(false)})
  it('rejects invalid snapshot and ping fields',()=>{const base={environmentKind:'Development',environmentDisplayName:'Development',hostVersion:'1',protocolVersion,totalModuleCount:1,validModuleCount:1,runningModuleCount:0,generatedAt:new Date().toISOString()};expect(isAppSnapshot({...base,totalModuleCount:-1})).toBe(false);expect(isAppSnapshot({...base,totalModuleCount:1.5})).toBe(false);expect(isAppSnapshot({...base,protocolVersion:3})).toBe(false);expect(isAppSnapshot({...base,generatedAt:'invalid'})).toBe(false);expect(isReadyChallenge({snapshot:base})).toBe(false);expect(isPingResponse({pong:false,hostTime:new Date().toISOString(),activated:true})).toBe(false)})
  it('rejects a mismatched response request id',async()=>{const transport=new MockTransport();transport.request=async request=>({protocolVersion,requestId:request.requestId+'bad',success:true,payload:{},error:null});await expect(new RequestClient(transport).request('app.ping')).rejects.toThrow('identity')})
  it('rejects protocol mismatch and unknown commands',async()=>{const transport=new MockTransport();expect((await transport.request({protocolVersion:1,requestId:'x',command:'app.ping',payload:{}})).success).toBe(false);await expect(new RequestClient(transport).request('bad')).rejects.toThrow('UnknownCommand')})
  it('dispatches known events and ignores malformed events',()=>{const dispatcher=new EventDispatcher();let value='';dispatcher.on('app.hostEvent',payload=>value=String(payload));for(const event of [null,'bad',{protocolVersion:1,event:'app.hostEvent',payload:'bad'}])dispatcher.dispatch(event);expect(value).toBe('');dispatcher.dispatch({protocolVersion,event:'app.hostEvent',payload:'ok'});expect(value).toBe('ok')})
  it('uses explicit unavailable transport instead of Mock',async()=>{const transport=new UnavailableTransport();expect(transport.mode).toBe('Unavailable');await expect(transport.request({protocolVersion,requestId:crypto.randomUUID(),command:'app.ping',payload:{}})).rejects.toThrow('unavailable')})
  it('rebuilds projected state after reload',()=>{setActivePinia(createPinia());const store=useAppStore();const first={environmentKind:'Mock',environmentDisplayName:'Mock A',hostVersion:'1',protocolVersion,totalModuleCount:1,validModuleCount:1,runningModuleCount:0,generatedAt:new Date().toISOString()};store.rebuild(first);store.rebuild({...first,totalModuleCount:4});expect(store.snapshot?.totalModuleCount).toBe(4)})
  it('disposes pending WebView requests and listeners',async()=>{const listeners=new Set<(event:MessageEvent)=>void>();const api={postMessage:()=>{},addEventListener:(_type:'message',listener:(event:MessageEvent)=>void)=>listeners.add(listener),removeEventListener:(_type:'message',listener:(event:MessageEvent)=>void)=>listeners.delete(listener)};Object.defineProperty(window,'chrome',{value:{webview:api},configurable:true});const transport=new WebViewTransport();const pending=transport.request({protocolVersion,requestId:crypto.randomUUID(),command:'app.ping',payload:{}});transport.dispose();await expect(pending).rejects.toThrow('disposed');expect(listeners.size).toBe(0)})
  it('rejects duplicate pending request ids',async()=>{const api={postMessage:()=>{},addEventListener:()=>{},removeEventListener:()=>{}};Object.defineProperty(window,'chrome',{value:{webview:api},configurable:true});const transport=new WebViewTransport();const request={protocolVersion,requestId:crypto.randomUUID(),command:'app.ping',payload:{}};void transport.request(request).catch(()=>{});await expect(transport.request(request)).rejects.toThrow('Duplicate');transport.dispose()})
})
