import { describe, expect, it } from 'vitest'
import { MockTransport } from '../transport/MockTransport'
import { RequestClient } from './RequestClient'
import { EventDispatcher } from './EventDispatcher'
import { isAppSnapshot, isPingResponse, isReadyChallenge, protocolVersion } from '../../contracts/app'
import { createPinia, setActivePinia } from 'pinia'
import { useAppStore } from '../../app/store'
import { WebViewTransport } from '../transport/WebViewTransport'
import { UnavailableTransport } from '../transport/UnavailableTransport'
import { AppClient } from '../clients/AppClient'

describe('Qing Bridge frontend', () => {
  it('requires activation before a snapshot', async()=>{await expect(new RequestClient(new MockTransport()).request('app.getSnapshot')).rejects.toThrow('BridgeNotActivated')})
  it('activates once and supports second and third session pings',async()=>{const client=new AppClient(new RequestClient(new MockTransport()));expect((await client.ready('Mock')).environmentKind).toBe('Mock');expect((await client.ping()).sessionToken).toBeTruthy();expect((await client.ping()).sessionToken).toBeUndefined();expect((await client.ping()).pong).toBe(true);expect((await client.getSnapshot()).environmentKind).toBe('Mock')})
  it('rejects a replayed activation nonce',async()=>{const transport=new MockTransport();const requests=new RequestClient(transport);const ready=await requests.request<{activationNonce:string}>('web.ready',{assetBuildId:'x',documentReadyState:'complete',transportMode:'Mock'});await requests.request('app.ping',{activationNonce:ready.activationNonce});await expect(requests.request('app.ping',{activationNonce:ready.activationNonce})).rejects.toThrow('InvalidActivationNonce')})
  it('rejects wrong and ambiguous session credentials',async()=>{const transport=new MockTransport();const requests=new RequestClient(transport);const ready=await requests.request<{activationNonce:string}>('web.ready',{});await requests.request('app.ping',{activationNonce:ready.activationNonce});await expect(requests.request('app.ping',{sessionToken:'wrong'})).rejects.toThrow('InvalidSessionToken');await expect(requests.request('app.ping',{activationNonce:'x',sessionToken:'y'})).rejects.toThrow('InvalidPingCredential')})
  it('disposes every activation credential',async()=>{const client=new AppClient(new RequestClient(new MockTransport()));await client.ready('Mock');await client.ping();client.dispose();await expect(client.ping()).rejects.toThrow('unavailable')})
  it('does not reuse a token after reload',async()=>{const first=new MockTransport();const requests=new RequestClient(first);const ready=await requests.request<{activationNonce:string}>('web.ready',{});const activated=await requests.request<{sessionToken:string}>('app.ping',{activationNonce:ready.activationNonce});first.dispose();const reloaded=new RequestClient(new MockTransport());await expect(reloaded.request('app.ping',{sessionToken:activated.sessionToken})).rejects.toThrow('BridgeNotActivated')})
  it('validates challenges snapshots session tokens and ping responses',()=>{const snapshot={environmentKind:'Development',environmentDisplayName:'Development',hostVersion:'1',protocolVersion,totalModuleCount:1,validModuleCount:1,runningModuleCount:0,generatedAt:new Date().toISOString()};expect(isAppSnapshot(snapshot)).toBe(true);expect(isReadyChallenge({activationNonce:'a'.repeat(64),snapshot})).toBe(true);expect(isPingResponse({pong:true,hostTime:new Date().toISOString(),sessionToken:'b'.repeat(64),activated:true})).toBe(true);expect(isPingResponse({pong:true,hostTime:new Date().toISOString(),sessionToken:'short',activated:true})).toBe(false)})
  it('rejects invalid snapshot and ping fields',()=>{const base={environmentKind:'Development',environmentDisplayName:'Development',hostVersion:'1',protocolVersion,totalModuleCount:1,validModuleCount:1,runningModuleCount:0,generatedAt:new Date().toISOString()};expect(isAppSnapshot({...base,totalModuleCount:-1})).toBe(false);expect(isAppSnapshot({...base,totalModuleCount:1.5})).toBe(false);expect(isAppSnapshot({...base,protocolVersion:3})).toBe(false);expect(isAppSnapshot({...base,generatedAt:'invalid'})).toBe(false);expect(isReadyChallenge({snapshot:base})).toBe(false);expect(isPingResponse({pong:false,hostTime:new Date().toISOString(),activated:true})).toBe(false)})
  it('rejects a mismatched response request id',async()=>{const transport=new MockTransport();transport.request=async request=>({protocolVersion,requestId:request.requestId+'bad',success:true,payload:{},error:null});await expect(new RequestClient(transport).request('app.ping')).rejects.toThrow('identity')})
  it('rejects protocol mismatch and unknown commands',async()=>{const transport=new MockTransport();expect((await transport.request({protocolVersion:1,requestId:'x',command:'app.ping',payload:{}})).success).toBe(false);await expect(new RequestClient(transport).request('bad')).rejects.toThrow('UnknownCommand')})
  it('dispatches known events and ignores malformed events',()=>{const dispatcher=new EventDispatcher();let value='';dispatcher.on('app.hostEvent',payload=>value=String(payload));for(const event of [null,'bad',{protocolVersion:1,event:'app.hostEvent',payload:'bad'}])dispatcher.dispatch(event);expect(value).toBe('');dispatcher.dispatch({protocolVersion,event:'app.hostEvent',payload:'ok'});expect(value).toBe('ok')})
  it('uses explicit unavailable transport instead of Mock',async()=>{const transport=new UnavailableTransport();expect(transport.mode).toBe('Unavailable');await expect(transport.request({protocolVersion,requestId:crypto.randomUUID(),command:'app.ping',payload:{}})).rejects.toThrow('unavailable')})
  it('rebuilds projected state after reload',()=>{setActivePinia(createPinia());const store=useAppStore();const first={environmentKind:'Mock',environmentDisplayName:'Mock A',hostVersion:'1',protocolVersion,totalModuleCount:1,validModuleCount:1,runningModuleCount:0,generatedAt:new Date().toISOString()};store.rebuild(first);store.rebuild({...first,totalModuleCount:4});expect(store.snapshot?.totalModuleCount).toBe(4)})
  it('disposes pending WebView requests and listeners',async()=>{const listeners=new Set<(event:MessageEvent)=>void>();const api={postMessage:()=>{},addEventListener:(_type:'message',listener:(event:MessageEvent)=>void)=>listeners.add(listener),removeEventListener:(_type:'message',listener:(event:MessageEvent)=>void)=>listeners.delete(listener)};Object.defineProperty(window,'chrome',{value:{webview:api},configurable:true});const transport=new WebViewTransport();const pending=transport.request({protocolVersion,requestId:crypto.randomUUID(),command:'app.ping',payload:{}});transport.dispose();await expect(pending).rejects.toThrow('disposed');expect(listeners.size).toBe(0)})
  it('rejects duplicate pending request ids',async()=>{const api={postMessage:()=>{},addEventListener:()=>{},removeEventListener:()=>{}};Object.defineProperty(window,'chrome',{value:{webview:api},configurable:true});const transport=new WebViewTransport();const request={protocolVersion,requestId:crypto.randomUUID(),command:'app.ping',payload:{}};void transport.request(request).catch(()=>{});await expect(transport.request(request)).rejects.toThrow('Duplicate');transport.dispose()})
})
