import { describe, expect, it } from 'vitest'
import { MockTransport } from '../transport/MockTransport'
import { RequestClient } from './RequestClient'
import { EventDispatcher } from './EventDispatcher'
import { isAppSnapshot, isPingResponse, isReadyChallenge, protocolVersion } from '../../contracts/app'
import { createPinia, setActivePinia } from 'pinia'
import { useAppStore } from '../../app/store'
import { WebViewTransport } from '../transport/WebViewTransport'
import { UnavailableTransport } from '../transport/UnavailableTransport'
import { AppClient } from '../clients/AppClient'

describe('Qing Bridge frontend', () => {
  it('returns an explicit mock snapshot', async () => { const c = new RequestClient(new MockTransport()); expect((await c.request<{environmentKind:string}>('app.getSnapshot')).environmentKind).toBe('Mock') })
  it('validates a ready challenge, snapshot and ping at runtime', async()=>{const snapshot={environmentKind:'Development',environmentDisplayName:'Development',hostVersion:'1',protocolVersion,totalModuleCount:1,validModuleCount:1,runningModuleCount:0,generatedAt:new Date().toISOString()};expect(isAppSnapshot(snapshot)).toBe(true);expect(isReadyChallenge({activationNonce:'a'.repeat(64),snapshot})).toBe(true);expect(isPingResponse({pong:true,hostTime:new Date().toISOString()})).toBe(true)})
  it('rejects invalid snapshot fields and challenges',()=>{const base={environmentKind:'Development',environmentDisplayName:'Development',hostVersion:'1',protocolVersion,totalModuleCount:1,validModuleCount:1,runningModuleCount:0,generatedAt:new Date().toISOString()};expect(isAppSnapshot({...base,totalModuleCount:-1})).toBe(false);expect(isAppSnapshot({...base,totalModuleCount:1.5})).toBe(false);expect(isAppSnapshot({...base,protocolVersion:2})).toBe(false);expect(isAppSnapshot({...base,generatedAt:'invalid'})).toBe(false);expect(isReadyChallenge({snapshot:base})).toBe(false);expect(isPingResponse({pong:false,hostTime:new Date().toISOString()})).toBe(false)})
  it('uses the challenge nonce for activation and clears it on dispose',async()=>{const transport=new MockTransport();const client=new AppClient(new RequestClient(transport));expect((await client.ready('Mock')).environmentKind).toBe('Mock');expect((await client.ping()).pong).toBe(true);client.dispose();await expect(client.ping()).rejects.toThrow('nonce')})
  it('rejects a mismatched response request id', async () => { const transport = new MockTransport(); transport.request = async request => ({ protocolVersion, requestId: request.requestId+'bad', success:true,payload:{},error:null }); await expect(new RequestClient(transport).request('app.ping')).rejects.toThrow('identity') })
  it('rejects protocol mismatch and unknown command', async () => { const transport = new MockTransport(); expect((await transport.request({protocolVersion:1,requestId:'x',command:'app.ping',payload:{}})).success).toBe(false); await expect(new RequestClient(transport).request('bad')).rejects.toThrow('UnknownCommand') })
  it('dispatches known events and safely ignores unknown events', () => { const d = new EventDispatcher(); let value=''; d.on('app.hostEvent', payload => value=String(payload)); d.dispatch({protocolVersion,event:'unknown',payload:'bad'}); expect(value).toBe(''); d.dispatch({protocolVersion,event:'app.hostEvent',payload:'ok'}); expect(value).toBe('ok') })
  it('safely ignores malformed and mismatched event messages', () => { const d=new EventDispatcher();let calls=0;d.on('app.hostEvent',()=>calls++);for(const value of [null,'bad',1,[],{protocolVersion:1,event:'app.hostEvent',payload:{}},{protocolVersion,event:4,payload:{}}])d.dispatch(value);expect(calls).toBe(0) })
  it('reports unavailable WebView transport outside WebView', async () => { const transport = new MockTransport(); transport.request = async () => { throw new Error('Transport unavailable') }; await expect(new RequestClient(transport).request('app.ping')).rejects.toThrow('unavailable') })
  it('uses an explicit unavailable transport instead of silently mocking', async () => { const transport=new UnavailableTransport();expect(transport.mode).toBe('Unavailable');await expect(transport.request({protocolVersion,requestId:crypto.randomUUID(),command:'app.ping',payload:{}})).rejects.toThrow('unavailable') })
  it('propagates a bounded transport timeout', async () => { const transport = new MockTransport(); transport.request = async () => { throw new Error('Bridge request timed out.') }; await expect(new RequestClient(transport).request('app.ping')).rejects.toThrow('timed out') })
  it('rebuilds projected state from a fresh snapshot after reload', () => { setActivePinia(createPinia()); const store = useAppStore(); const first = { environmentKind:'Mock', environmentDisplayName:'Mock A', hostVersion:'1', protocolVersion, totalModuleCount:1, validModuleCount:1, runningModuleCount:0, generatedAt:new Date().toISOString() }; store.rebuild(first); store.rebuild({ ...first, totalModuleCount: 4, generatedAt:new Date().toISOString() }); expect(store.snapshot?.totalModuleCount).toBe(4) })
  it('disposes listeners, timers and pending WebView requests', async () => { const listeners=new Set<(event:MessageEvent)=>void>();const api={postMessage:()=>{},addEventListener:(_type:'message',listener:(event:MessageEvent)=>void)=>listeners.add(listener),removeEventListener:(_type:'message',listener:(event:MessageEvent)=>void)=>listeners.delete(listener)};Object.defineProperty(window,'chrome',{value:{webview:api},configurable:true});const transport=new WebViewTransport();const id=crypto.randomUUID();const pending=transport.request({protocolVersion,requestId:id,command:'app.ping',payload:{}});transport.dispose();await expect(pending).rejects.toThrow('disposed');expect(listeners.size).toBe(0);await expect(transport.request({protocolVersion,requestId:crypto.randomUUID(),command:'app.ping',payload:{}})).rejects.toThrow('disposed') })
  it('rejects duplicate pending request ids', async () => { const api={postMessage:()=>{},addEventListener:()=>{},removeEventListener:()=>{}};Object.defineProperty(window,'chrome',{value:{webview:api},configurable:true});const transport=new WebViewTransport();const request={protocolVersion,requestId:crypto.randomUUID(),command:'app.ping',payload:{}};void transport.request(request).catch(()=>{});await expect(transport.request(request)).rejects.toThrow('Duplicate');transport.dispose() })
})
