//! Bounded diagnostic metadata only. Never accepts message bodies, names, paths or raw errors.
use crate::{now_rfc3339, SessionLogEntry};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::{
    collections::{BTreeMap, VecDeque},
    fs::{self, OpenOptions},
    io::{self, Write},
    path::{Path, PathBuf},
    sync::{mpsc, Mutex, OnceLock},
    thread,
    time::{Duration, Instant},
};

const LIMIT: usize = 256;
const FILE_LIMIT: u64 = 128 * 1024;

#[derive(Clone, Copy, Debug, Serialize, Deserialize)]
pub(crate) enum Level {
    Information,
    Warning,
    Error,
}
#[derive(Clone, Copy, Debug, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub(crate) enum Event {
    DiscoveryStarted,
    DiscoveryStopped,
    EndpointResolved,
    EndpointLost,
    DiscoveryRefresh,
    EndpointConnectStarted,
    EndpointConnectFailed,
    HandshakeTransportFailed,
    ManagementAckFailed,
    IncomingManagementFailed,
    ProbeFailed,
    HandshakeStarted,
    HandshakeSucceeded,
    HandshakeFailed,
    HeartbeatSkipped,
    PeerOnline,
    PeerOffline,
    NoticeConsumed,
    NotificationReceived,
    NotificationQueued,
    NotificationSkipped,
    NotificationPopupShown,
    NotificationPopupFailed,
    BatteryReceived,
    TransferConnect,
    TransferConnected,
    TransferOfferSent,
    TransferOfferReceived,
    TransferAccepted,
    TransferRejected,
    TransferCompleted,
    TransferFailed,
    LogStorageFailed,
    LogEntriesDropped,
}
#[derive(Clone, Copy, Debug, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub(crate) enum Reason {
    None,
    Network,
    Protocol,
    IdentityMismatch,
    PermissionRevoked,
    Duplicate,
    ChannelBusy,
    AlreadyInFlight,
    AuthNotFresh,
    NoEndpoint,
    SessionInactive,
    Unexpected,
    EndpointExpired,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Entry {
    at: String,
    level: Level,
    event: Event,
    reason: Reason,
    peer: String,
    request: String,
}

fn token(value: Option<&str>) -> String {
    value
        .map(|value| {
            Sha256::digest(value.as_bytes())[..6]
                .iter()
                .map(|byte| format!("{byte:02x}"))
                .collect()
        })
        .unwrap_or_else(|| "-".into())
}
fn symbol(value: &impl Serialize) -> String {
    serde_json::to_string(value)
        .unwrap_or_default()
        .trim_matches('"')
        .to_owned()
}
impl Entry {
    fn new(
        level: Level,
        event: Event,
        reason: Reason,
        peer: Option<&str>,
        request: Option<&str>,
    ) -> Self {
        Self {
            at: now_rfc3339(),
            level,
            event,
            reason,
            peer: token(peer),
            request: token(request),
        }
    }
    fn valid(&self) -> bool {
        let valid_token = |value: &str| {
            value == "-"
                || value.len() == 12
                    && value
                        .bytes()
                        .all(|b| b.is_ascii_hexdigit() && !b.is_ascii_uppercase())
        };
        // UTC timestamps generated by the host; do not display arbitrary disk text.
        self.at.len() == 24
            && self.at.bytes().enumerate().all(|(index, b)| match index {
                4 | 7 => b == b'-',
                10 => b == b'T',
                13 | 16 => b == b':',
                19 => b == b'.',
                23 => b == b'Z',
                _ => b.is_ascii_digit(),
            })
            && valid_token(&self.peer)
            && valid_token(&self.request)
    }
    fn session(&self) -> SessionLogEntry {
        SessionLogEntry {
            timestamp: self.at.clone(),
            level: symbol(&self.level),
            category: "DeviceLink".into(),
            message: format!(
                "event={} reason={} peer={} request={}",
                symbol(&self.event),
                symbol(&self.reason),
                self.peer,
                self.request
            ),
        }
    }
}

#[derive(Default)]
struct Buffer {
    entries: VecDeque<Entry>,
    repeated: BTreeMap<String, Instant>,
}
impl Buffer {
    fn add(&mut self, entry: Entry, throttle: bool) -> bool {
        if throttle {
            let key = format!(
                "{:?}:{:?}:{}:{}",
                entry.event, entry.reason, entry.peer, entry.request
            );
            if self
                .repeated
                .get(&key)
                .is_some_and(|time| time.elapsed() < Duration::from_secs(30))
            {
                return false;
            }
            if self.repeated.len() >= LIMIT {
                if let Some(oldest) = self
                    .repeated
                    .iter()
                    .min_by_key(|(_, time)| *time)
                    .map(|(key, _)| key.clone())
                {
                    self.repeated.remove(&oldest);
                }
            }
            self.repeated.insert(key, Instant::now());
        }
        self.entries.push_back(entry);
        while self.entries.len() > LIMIT {
            self.entries.pop_front();
        }
        true
    }
}
struct Journal {
    path: PathBuf,
}
impl Journal {
    fn previous(&self) -> PathBuf {
        self.path.with_extension("log.1")
    }
    fn read(&self) -> Vec<Entry> {
        [self.previous(), self.path.clone()]
            .iter()
            .flat_map(|path| {
                if !fs::metadata(path).is_ok_and(|meta| meta.len() <= FILE_LIMIT + 1024) {
                    return vec![];
                }
                fs::read_to_string(path)
                    .unwrap_or_default()
                    .lines()
                    .filter_map(|line| serde_json::from_str::<Entry>(line).ok())
                    .filter(Entry::valid)
                    .collect::<Vec<_>>()
            })
            .collect()
    }
    fn append(&self, entry: &Entry) -> io::Result<()> {
        if !entry.valid() {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "invalid diagnostic metadata",
            ));
        }
        if let Some(parent) = self.path.parent() {
            fs::create_dir_all(parent)?;
        }
        let line = serde_json::to_string(entry)? + "\n";
        if fs::metadata(&self.path).is_ok_and(|meta| meta.len() + line.len() as u64 > FILE_LIMIT) {
            let previous = self.previous();
            if previous.exists() {
                fs::remove_file(&previous)?;
            }
            fs::rename(&self.path, previous)?;
        }
        OpenOptions::new()
            .create(true)
            .append(true)
            .open(&self.path)?
            .write_all(line.as_bytes())
    }
}
struct Diagnostics {
    buffer: Mutex<Buffer>,
    writer: Option<mpsc::SyncSender<Entry>>,
}
static DIAGNOSTICS: OnceLock<Diagnostics> = OnceLock::new();

pub(crate) fn initialize(profile: Option<&Path>) {
    if DIAGNOSTICS.get().is_some() {
        return;
    }
    #[cfg(test)]
    let profile = {
        let _ = profile;
        None::<&Path>
    };
    let journal = profile.map(|root| Journal {
        path: root.join("Logs").join("devices.log"),
    });
    let mut buffer = Buffer::default();
    if let Some(journal) = &journal {
        for entry in journal.read() {
            buffer.add(entry, false);
        }
    }
    let (sender, receiver) = mpsc::sync_channel::<Entry>(LIMIT);
    let persist = journal.is_some();
    if DIAGNOSTICS
        .set(Diagnostics {
            buffer: Mutex::new(buffer),
            writer: persist.then_some(sender),
        })
        .is_err()
    {
        return;
    }
    if let Some(journal) = journal {
        thread::spawn(move || {
            let mut warned = false;
            while let Ok(entry) = receiver.recv() {
                if journal.append(&entry).is_err() && !warned {
                    warned = true;
                    if let Some(diagnostics) = DIAGNOSTICS.get() {
                        diagnostics
                            .buffer
                            .lock()
                            .unwrap_or_else(|e| e.into_inner())
                            .add(
                                Entry::new(
                                    Level::Warning,
                                    Event::LogStorageFailed,
                                    Reason::Unexpected,
                                    None,
                                    None,
                                ),
                                false,
                            );
                    }
                }
            }
        });
    }
}

pub(crate) fn record(
    level: Level,
    event: Event,
    reason: Reason,
    peer: Option<&str>,
    request: Option<&str>,
    throttle: bool,
) {
    let Some(diagnostics) = DIAGNOSTICS.get() else {
        return;
    };
    let entry = Entry::new(level, event, reason, peer, request);
    let mut buffer = diagnostics.buffer.lock().unwrap_or_else(|e| e.into_inner());
    if !buffer.add(entry.clone(), throttle) {
        return;
    }
    if diagnostics
        .writer
        .as_ref()
        .is_some_and(|sender| sender.try_send(entry).is_err())
    {
        buffer.add(
            Entry::new(
                Level::Warning,
                Event::LogEntriesDropped,
                Reason::ChannelBusy,
                None,
                None,
            ),
            true,
        );
    }
}
pub(crate) fn snapshot() -> Vec<SessionLogEntry> {
    DIAGNOSTICS
        .get()
        .map(|diagnostics| {
            diagnostics
                .buffer
                .lock()
                .unwrap_or_else(|e| e.into_inner())
                .entries
                .iter()
                .map(Entry::session)
                .collect()
        })
        .unwrap_or_default()
}

/// Classification only: the supplied error itself is never retained or displayed in diagnostics.
pub(crate) fn failure_reason(error: &str) -> Reason {
    if error.contains("身份") || error.contains("未配对") {
        Reason::IdentityMismatch
    } else if error.contains("超时")
        || error.contains("连接")
        || error.contains("timed out")
        || error.contains("os error")
    {
        Reason::Network
    } else if error.contains("协议") || error.contains("加密") || error.contains("帧") {
        Reason::Protocol
    } else {
        Reason::Unexpected
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn metadata_is_hashed_and_disk_schema_rejects_raw_identifiers() {
        let mut entry = Entry::new(
            Level::Information,
            Event::NotificationReceived,
            Reason::None,
            Some("secret-peer"),
            Some("request"),
        );
        assert!(entry.valid());
        assert_eq!(entry.request, "1f58b9145b24"); // Cross-language SHA-256 truncated token.
        let line = serde_json::to_string(&entry).unwrap();
        assert!(!line.contains("secret-peer"));
        entry.peer = "private contents".into();
        assert!(!entry.valid());
        assert!(serde_json::from_str::<Entry>(&line.replace("\"event\":", "\"body\":")).is_err());
    }
    #[test]
    fn buffer_and_throttle_are_bounded() {
        let mut buffer = Buffer::default();
        for n in 0..600 {
            buffer.add(
                Entry::new(
                    Level::Information,
                    Event::HandshakeStarted,
                    Reason::None,
                    Some(&n.to_string()),
                    None,
                ),
                true,
            );
        }
        assert_eq!(buffer.entries.len(), LIMIT);
        assert_eq!(buffer.repeated.len(), LIMIT);
        let entry = Entry::new(
            Level::Warning,
            Event::ProbeFailed,
            Reason::Network,
            Some("peer"),
            None,
        );
        assert!(buffer.add(entry.clone(), true));
        assert!(!buffer.add(entry, true));
    }
    #[test]
    fn endpoint_attempts_are_distinct_but_raw_addresses_are_not_retained() {
        let mut buffer = Buffer::default();
        let first = Entry::new(
            Level::Warning,
            Event::EndpointConnectFailed,
            Reason::Network,
            Some("paired-key"),
            Some("192.168.1.3:42577"),
        );
        let second = Entry::new(
            Level::Warning,
            Event::EndpointConnectFailed,
            Reason::Network,
            Some("paired-key"),
            Some("[fe80::1234]:42577"),
        );
        assert!(buffer.add(first.clone(), true));
        assert!(!buffer.add(first, true));
        assert!(buffer.add(second.clone(), true));
        let line = serde_json::to_string(&second).unwrap();
        assert!(serde_json::from_str::<Entry>(&line).unwrap().valid());
        assert!(!line.contains("fe80") && !line.contains("paired-key"));
    }
    #[test]
    fn journal_rotates_and_reloads_only_approved_metadata() {
        let root = std::env::temp_dir().join(format!(
            "qing-device-log-{}-{}",
            std::process::id(),
            crate::now_rfc3339().replace(':', "")
        ));
        let journal = Journal {
            path: root.join("devices.log"),
        };
        let entry = Entry::new(
            Level::Information,
            Event::TransferCompleted,
            Reason::None,
            None,
            None,
        );
        for _ in 0..1800 {
            journal.append(&entry).unwrap();
        }
        assert!(fs::metadata(&journal.path).unwrap().len() <= FILE_LIMIT);
        assert!(fs::metadata(journal.previous()).unwrap().len() <= FILE_LIMIT);
        assert!(!journal.read().is_empty());
        fs::remove_file(&journal.path).unwrap();
        fs::remove_file(journal.previous()).unwrap();
        fs::remove_dir(root).unwrap();
    }
}
