use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
    time::{SystemTime, UNIX_EPOCH},
};

use base64::{engine::general_purpose::STANDARD as BASE64, Engine as _};
use serde::{Deserialize, Serialize};

use crate::paths::{
    canonical_manifest_path, canonical_module_directory, resolve_existing_asset, summarize_root,
    ModuleRoot, ModuleRootSummary, ModuleSource,
};

const MAX_MANIFEST_BYTES: u64 = 128 * 1024;
const MAX_ICON_BYTES: u64 = 512 * 1024;
const MAX_ID_LENGTH: usize = 128;
const MAX_NAME_LENGTH: usize = 256;
const MAX_DESCRIPTION_LENGTH: usize = 4096;
const MAX_VERSION_LENGTH: usize = 64;
const MAX_AUTHOR_LENGTH: usize = 256;
const MAX_OPERATION_LENGTH: usize = 64;
const MAX_OPERATIONS: usize = 64;

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ModuleIssue {
    pub code: String,
    pub message: String,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ModuleSummary {
    pub id: String,
    pub name: String,
    pub description: Option<String>,
    pub version: String,
    pub author: Option<String>,
    pub ui_kind: Option<String>,
    pub runtime_type: Option<String>,
    pub runtime_isolation: Option<String>,
    pub source: ModuleSource,
    /// A bounded data URL generated by the backend. The frontend never gets
    /// a filesystem path that it could submit back to the host.
    pub icon_data_url: Option<String>,
    pub valid: bool,
    pub issues: Vec<ModuleIssue>,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ModuleListPayload {
    pub modules: Vec<ModuleSummary>,
    pub roots: Vec<ModuleRootSummary>,
    pub scanned_at_unix_ms: u64,
}

/// Backend-only record. The frontend receives an id and never receives a path
/// that it could submit back as an execution request.
#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct ModuleRecord {
    pub name: String,
    pub version: String,
    /// Safe presentation data copied from the validated manifest icon. The
    /// backend keeps the source path private while module Web windows may
    /// render the same icon as the host module card.
    pub icon_data_url: Option<String>,
    pub directory: PathBuf,
    pub entry: PathBuf,
    /// Manifest-relative entry route for a validated `uiKind=Web` module. The
    /// frontend does not receive this path; the host resolves it on demand.
    pub web_entry: Option<String>,
    /// Operations the module explicitly exposes through `module.invoke`.
    /// An omitted/empty list means that the module has no host-call surface.
    pub operations: BTreeSet<String>,
    pub source: ModuleSource,
}

#[derive(Debug)]
pub struct DiscoveryResult {
    pub payload: ModuleListPayload,
    pub records: BTreeMap<String, ModuleRecord>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RawManifest {
    id: Option<String>,
    name: Option<String>,
    description: Option<String>,
    version: Option<String>,
    author: Option<String>,
    entry: Option<String>,
    icon: Option<String>,
    web_entry: Option<String>,
    runtime_type: Option<String>,
    runtime_isolation: Option<String>,
    ui_kind: Option<String>,
    load_mode: Option<String>,
    permissions: Option<Vec<serde_json::Value>>,
    operations: Option<Vec<String>>,
    #[allow(dead_code)]
    minimum_host_version: Option<String>,
    #[allow(dead_code)]
    default_language: Option<String>,
}

pub fn discover_modules(roots: &[ModuleRoot]) -> DiscoveryResult {
    let mut modules = Vec::new();
    let mut records = BTreeMap::new();
    let mut seen_ids = BTreeSet::new();
    let root_summaries = roots.iter().map(summarize_root).collect::<Vec<_>>();

    // Root order is intentional: bundled modules win over user modules with
    // the same id, matching the host's development-directory precedence.
    for root in roots {
        let canonical_root = match fs::canonicalize(&root.path) {
            Ok(path) if path.is_dir() => path,
            _ => continue,
        };

        let mut directories = match fs::read_dir(&canonical_root) {
            Ok(entries) => entries
                .filter_map(Result::ok)
                .filter_map(|entry| {
                    let file_type = entry.file_type().ok()?;
                    if !file_type.is_dir() {
                        return None;
                    }
                    Some(entry.path())
                })
                .collect::<Vec<_>>(),
            Err(_) => continue,
        };
        directories.sort_by(|left, right| left.file_name().cmp(&right.file_name()));

        for candidate in directories {
            let directory = match canonical_module_directory(&canonical_root, &candidate) {
                Ok(path) => path,
                Err(_) => continue,
            };
            let directory_name = directory
                .file_name()
                .and_then(|name| name.to_str())
                .unwrap_or("unknown-module")
                .to_string();
            let manifest_path = match canonical_manifest_path(&directory) {
                Ok(path) => path,
                Err(error) => {
                    modules.push(invalid_summary(
                        directory_name,
                        root.source,
                        "manifestMissing",
                        format!("无法读取 module.json：{error}"),
                    ));
                    continue;
                }
            };

            let manifest = match read_manifest(&manifest_path) {
                Ok(manifest) => manifest,
                Err((code, message)) => {
                    modules.push(invalid_summary(directory_name, root.source, &code, message));
                    continue;
                }
            };

            let (summary, id) = validate_manifest(&manifest, &directory, root.source);
            // Invalid/empty ids cannot be used as backend lookup keys. Keep
            // their diagnostics visible, but never allow a duplicate valid id
            // from a lower-priority root to replace the first one.
            if let Some(id) = id {
                if seen_ids.contains(&id) {
                    continue;
                }
                seen_ids.insert(id.clone());
                let entry = manifest
                    .entry
                    .as_deref()
                    .and_then(|value| resolve_existing_asset(&directory, value).ok())
                    .expect("valid manifest must have a resolved entry");
                let web_entry = manifest
                    .ui_kind
                    .as_deref()
                    .filter(|kind| *kind == "Web")
                    .and(manifest.web_entry.as_deref())
                    .map(str::to_string);
                let operations = manifest
                    .operations
                    .clone()
                    .unwrap_or_default()
                    .into_iter()
                    .collect::<BTreeSet<_>>();
                let icon_data_url = summary.icon_data_url.clone();
                let record_id = id.clone();
                records.insert(
                    id,
                    ModuleRecord {
                        name: manifest.name.clone().unwrap_or(record_id),
                        version: manifest
                            .version
                            .clone()
                            .unwrap_or_else(|| "0.0.0".to_string()),
                        icon_data_url,
                        directory,
                        entry,
                        web_entry,
                        operations,
                        source: root.source,
                    },
                );
            }
            modules.push(summary);
        }
    }

    modules.sort_by(|left, right| {
        left.name
            .to_ascii_lowercase()
            .cmp(&right.name.to_ascii_lowercase())
            .then_with(|| left.id.cmp(&right.id))
    });

    DiscoveryResult {
        payload: ModuleListPayload {
            modules,
            roots: root_summaries,
            scanned_at_unix_ms: unix_time_millis(),
        },
        records,
    }
}

fn read_manifest(path: &Path) -> Result<RawManifest, (String, String)> {
    let metadata = fs::metadata(path).map_err(|error| {
        (
            "manifestUnreadable".to_string(),
            format!("无法读取 module.json：{error}"),
        )
    })?;
    if metadata.len() > MAX_MANIFEST_BYTES {
        return Err((
            "manifestTooLarge".to_string(),
            "module.json 超过 128 KiB 限制。".to_string(),
        ));
    }
    let bytes = fs::read(path).map_err(|error| {
        (
            "manifestUnreadable".to_string(),
            format!("无法读取 module.json：{error}"),
        )
    })?;
    serde_json::from_slice(&bytes).map_err(|error| {
        (
            "manifestInvalidJson".to_string(),
            format!("module.json 不是有效 JSON：{error}"),
        )
    })
}

fn validate_manifest(
    manifest: &RawManifest,
    directory: &Path,
    source: ModuleSource,
) -> (ModuleSummary, Option<String>) {
    let mut issues = Vec::new();
    let id = manifest.id.as_deref().unwrap_or("").trim().to_string();
    let name = manifest.name.as_deref().unwrap_or("").trim().to_string();
    let version = manifest.version.as_deref().unwrap_or("").trim().to_string();

    if id.is_empty() {
        issues.push(issue("missingId", "缺少模块 id。"));
    } else if id.chars().count() > MAX_ID_LENGTH
        || !id
            .chars()
            .next()
            .is_some_and(|character| character.is_ascii_alphanumeric())
        || !id
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || ".-_".contains(character))
    {
        issues.push(issue(
            "invalidId",
            "模块 id 只能包含字母、数字、点、短横线和下划线。",
        ));
    }
    if name.is_empty() {
        issues.push(issue("missingName", "缺少模块 name。"));
    } else if name.chars().count() > MAX_NAME_LENGTH {
        issues.push(issue("nameTooLong", "模块 name 超过长度限制。"));
    }
    if version.is_empty() {
        issues.push(issue("missingVersion", "缺少模块 version。"));
    } else if version.chars().count() > MAX_VERSION_LENGTH {
        issues.push(issue("versionTooLong", "模块 version 超过长度限制。"));
    }
    if manifest
        .description
        .as_deref()
        .is_some_and(|value| value.chars().count() > MAX_DESCRIPTION_LENGTH)
    {
        issues.push(issue(
            "descriptionTooLong",
            "模块 description 超过长度限制。",
        ));
    }
    if manifest
        .author
        .as_deref()
        .is_some_and(|value| value.chars().count() > MAX_AUTHOR_LENGTH)
    {
        issues.push(issue("authorTooLong", "模块 author 超过长度限制。"));
    }

    match manifest.runtime_type.as_deref() {
        Some("Process") => {}
        Some(value) => issues.push(issue(
            "runtimeTypeUnsupported",
            format!("新宿主只支持 Process 模块运行时：{value}"),
        )),
        None => issues.push(issue(
            "runtimeTypeMissing",
            "新宿主模块必须声明 runtimeType=Process。",
        )),
    }
    match manifest.runtime_isolation.as_deref() {
        Some("OutOfProcess") => {}
        Some(value) => issues.push(issue(
            "runtimeIsolationUnsupported",
            format!("新宿主只支持 OutOfProcess 模块隔离：{value}"),
        )),
        None => issues.push(issue(
            "runtimeIsolationMissing",
            "新宿主模块必须声明 runtimeIsolation=OutOfProcess。",
        )),
    }

    match manifest.load_mode.as_deref() {
        Some("Manual" | "Startup") => {}
        Some(value) => issues.push(issue(
            "loadModeUnsupported",
            format!("模块 loadMode 只支持 Manual 或 Startup：{value}"),
        )),
        None => issues.push(issue("loadModeMissing", "新宿主模块必须声明 loadMode。")),
    }

    validate_permissions(manifest.permissions.as_deref(), &mut issues);
    validate_operations(manifest.operations.as_deref(), &mut issues);

    match manifest.entry.as_deref() {
        Some(entry)
            if resolve_existing_asset(directory, entry).is_ok()
                && supported_entry_extension(entry) => {}
        Some(entry) if resolve_existing_asset(directory, entry).is_ok() => issues.push(issue(
            "entryTypeUnsupported",
            "新宿主模块 entry 必须是 Windows executable（.exe）。",
        )),
        Some(entry) => issues.push(issue(
            "entryInvalid",
            format!("模块 entry 路径无效或不存在：{entry}"),
        )),
        None => issues.push(issue("missingEntry", "缺少模块 entry。")),
    }

    let icon_data_url = match manifest.icon.as_deref() {
        Some(icon) if resolve_existing_asset(directory, icon).is_ok() => {
            read_icon_data_url(directory, icon, &mut issues)
        }
        Some(icon) => {
            issues.push(issue(
                "iconInvalid",
                format!("模块 icon 路径无效或不存在：{icon}"),
            ));
            None
        }
        None => None,
    };

    if manifest
        .ui_kind
        .as_deref()
        .is_some_and(|kind| kind != "Web" && kind != "None")
    {
        issues.push(issue(
            "uiKindUnsupported",
            "模块 uiKind 只支持 None 或 Web。",
        ));
    }

    if manifest
        .ui_kind
        .as_deref()
        .is_some_and(|kind| kind == "Web")
    {
        match manifest.web_entry.as_deref() {
            Some(web_entry)
                if valid_web_entry_route(web_entry)
                    && web_entry.to_ascii_lowercase().ends_with(".html")
                    && resolve_existing_asset(directory, web_entry).is_ok() => {}
            Some(web_entry) => issues.push(issue(
                "webEntryInvalid",
                format!("Web 模块 webEntry 路径无效或不存在：{web_entry}"),
            )),
            None => issues.push(issue("webEntryMissing", "Web 模块缺少 webEntry。")),
        }
    }

    let valid = issues.is_empty();
    let id_for_summary = if id.is_empty() {
        directory
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("unknown-module")
            .to_string()
    } else {
        id.clone()
    };
    let summary = ModuleSummary {
        id: id_for_summary,
        name: if name.is_empty() {
            "未命名模块".to_string()
        } else {
            name
        },
        description: clean_optional(manifest.description.as_deref()),
        version: version_or_placeholder(&version),
        author: clean_optional(manifest.author.as_deref()),
        ui_kind: clean_optional(manifest.ui_kind.as_deref()),
        runtime_type: clean_optional(manifest.runtime_type.as_deref()),
        runtime_isolation: clean_optional(manifest.runtime_isolation.as_deref()),
        source,
        icon_data_url,
        valid,
        issues,
    };

    let lookup_id = if valid { Some(id) } else { None };
    (summary, lookup_id)
}

fn supported_entry_extension(value: &str) -> bool {
    if cfg!(windows) {
        value
            .rsplit(['/', '\\'])
            .next()
            .and_then(|name| name.rsplit_once('.'))
            .is_some_and(|(_, extension)| extension.eq_ignore_ascii_case("exe"))
    } else {
        true
    }
}

fn valid_web_entry_route(value: &str) -> bool {
    !value.is_empty()
        && !value.contains(['\\', '%', '?', '#', ' '])
        && value
            .split('/')
            .all(|segment| !segment.is_empty() && segment != "." && segment != "..")
}

fn validate_permissions(permissions: Option<&[serde_json::Value]>, issues: &mut Vec<ModuleIssue>) {
    let Some(permissions) = permissions else {
        return;
    };
    if permissions.len() > 32 {
        issues.push(issue(
            "permissionsTooMany",
            "模块 permissions 不得超过 32 项。",
        ));
        return;
    }
    const ALLOWED: &[&str] = &[
        "FileRead",
        "FileWrite",
        "ProcessStart",
        "Network",
        "Clipboard",
        "WindowControl",
    ];
    let mut seen = std::collections::BTreeSet::new();
    for value in permissions {
        let Some(value) = value.as_str() else {
            issues.push(issue("permissionInvalid", "模块 permission 必须是字符串。"));
            continue;
        };
        if !ALLOWED.contains(&value) || !seen.insert(value) {
            issues.push(issue(
                "permissionInvalid",
                format!("模块 permission 未知或重复：{value}"),
            ));
        }
    }
}

fn validate_operations(operations: Option<&[String]>, issues: &mut Vec<ModuleIssue>) {
    let Some(operations) = operations else {
        return;
    };
    if operations.len() > MAX_OPERATIONS {
        issues.push(issue(
            "operationsTooMany",
            format!("模块 operations 不得超过 {MAX_OPERATIONS} 项。"),
        ));
        return;
    }
    let mut seen = BTreeSet::new();
    for operation in operations {
        if operation.is_empty()
            || operation.len() > MAX_OPERATION_LENGTH
            || !operation
                .bytes()
                .next()
                .is_some_and(|byte| byte.is_ascii_alphanumeric())
            || !operation.bytes().all(|byte| {
                byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'-' | b'_' | b':')
            })
            || !seen.insert(operation)
        {
            issues.push(issue(
                "operationInvalid",
                format!("模块 operation 无效或重复：{operation}"),
            ));
        }
    }
}

fn invalid_summary(id: String, source: ModuleSource, code: &str, message: String) -> ModuleSummary {
    ModuleSummary {
        id: id.clone(),
        name: id,
        description: None,
        version: "—".to_string(),
        author: None,
        ui_kind: None,
        runtime_type: None,
        runtime_isolation: None,
        source,
        icon_data_url: None,
        valid: false,
        issues: vec![issue(code, message)],
    }
}

fn read_icon_data_url(
    directory: &Path,
    relative: &str,
    issues: &mut Vec<ModuleIssue>,
) -> Option<String> {
    let path = match resolve_existing_asset(directory, relative) {
        Ok(path) => path,
        Err(error) => {
            issues.push(issue("iconInvalid", format!("模块 icon 路径无效：{error}")));
            return None;
        }
    };
    let metadata = match fs::metadata(&path) {
        Ok(metadata) => metadata,
        Err(error) => {
            issues.push(issue(
                "iconUnreadable",
                format!("无法读取模块 icon：{error}"),
            ));
            return None;
        }
    };
    if metadata.len() > MAX_ICON_BYTES {
        issues.push(issue("iconTooLarge", "模块 icon 超过 512 KiB 限制。"));
        return None;
    }
    let bytes = match fs::read(&path) {
        Ok(bytes) => bytes,
        Err(error) => {
            issues.push(issue(
                "iconUnreadable",
                format!("无法读取模块 icon：{error}"),
            ));
            return None;
        }
    };
    let extension = path
        .extension()
        .and_then(|value| value.to_str())
        .map(|value| value.to_ascii_lowercase());
    let mime = match extension.as_deref() {
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("jpg") | Some("jpeg") => "image/jpeg",
        Some("ico") => "image/x-icon",
        _ => {
            issues.push(issue(
                "iconTypeUnsupported",
                "模块 icon 只支持 SVG、PNG、JPEG 或 ICO。",
            ));
            return None;
        }
    };
    Some(format!("data:{mime};base64,{}", BASE64.encode(bytes)))
}

fn issue(code: &str, message: impl Into<String>) -> ModuleIssue {
    ModuleIssue {
        code: code.to_string(),
        message: message.into(),
    }
}

fn clean_optional(value: Option<&str>) -> Option<String> {
    value
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(str::to_string)
}

fn version_or_placeholder(value: &str) -> String {
    if value.is_empty() {
        "—".to_string()
    } else {
        value.to_string()
    }
}

fn unix_time_millis() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_millis().min(u64::MAX as u128) as u64)
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::{
        env, fs,
        time::{SystemTime, UNIX_EPOCH},
    };

    fn temp_module(name: &str, manifest: &str) -> (PathBuf, ModuleRoot) {
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("clock")
            .as_nanos();
        let temp = env::temp_dir().join(format!(
            "qingtoolbox-tauri-test-{}-{nonce}",
            std::process::id()
        ));
        fs::create_dir_all(&temp).expect("temp dir");
        let module = temp.join(name);
        fs::create_dir_all(&module).expect("module dir");
        fs::write(module.join("module.json"), manifest).expect("manifest");
        fs::write(module.join("entry.exe"), b"placeholder").expect("entry");
        (
            temp.clone(),
            ModuleRoot {
                source: ModuleSource::Bundled,
                path: temp,
            },
        )
    }

    #[test]
    fn discovers_valid_manifest_without_loading_entry() {
        let (temp, root) = temp_module(
            "demo",
            r#"{"id":"demo.test","name":"Demo","version":"1.0.0","entry":"entry.exe","runtimeType":"Process","runtimeIsolation":"OutOfProcess","loadMode":"Manual"}"#,
        );
        let result = discover_modules(&[root]);
        assert_eq!(result.payload.modules.len(), 1);
        assert!(result.payload.modules[0].valid);
        assert!(result.records.contains_key("demo.test"));
        let _ = fs::remove_dir_all(temp);
    }

    #[test]
    fn icon_is_returned_as_a_bounded_data_url_not_a_path() {
        let (temp, root) = temp_module(
            "icon-demo",
            r#"{"id":"demo.icon","name":"Icon Demo","version":"1.0.0","entry":"entry.exe","runtimeType":"Process","runtimeIsolation":"OutOfProcess","loadMode":"Manual","icon":"icon.svg"}"#,
        );
        fs::write(
            temp.join("icon-demo").join("icon.svg"),
            br#"<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1 1"><path d="M0 0h1v1H0z"/></svg>"#,
        )
        .expect("icon");
        let result = discover_modules(&[root]);
        let summary = &result.payload.modules[0];
        assert!(summary.valid);
        assert!(summary.icon_data_url.as_deref().is_some_and(|value| {
            value.starts_with("data:image/svg+xml;base64,") && !value.contains("icon.svg")
        }));
        let _ = fs::remove_dir_all(temp);
    }

    #[test]
    fn web_manifest_keeps_only_a_relative_entry_route_in_the_backend_record() {
        let (temp, root) = temp_module(
            "web-demo",
            r#"{"id":"demo.web","name":"Web Demo","version":"1.0.0","entry":"entry.exe","runtimeType":"Process","runtimeIsolation":"OutOfProcess","uiKind":"Web","webEntry":"ui/index.html","loadMode":"Manual"}"#,
        );
        fs::create_dir_all(temp.join("web-demo").join("ui")).expect("ui dir");
        fs::write(
            temp.join("web-demo").join("ui").join("index.html"),
            "<html />",
        )
        .expect("web entry");
        let result = discover_modules(&[root]);
        assert!(result.payload.modules[0].valid);
        assert_eq!(
            result.records["demo.web"].web_entry.as_deref(),
            Some("ui/index.html")
        );
        let _ = fs::remove_dir_all(temp);
    }

    #[test]
    fn declared_operations_are_kept_backend_only() {
        let (temp, root) = temp_module(
            "operations",
            r#"{"id":"demo.operations","name":"Operations","version":"1.0.0","entry":"entry.exe","runtimeType":"Process","runtimeIsolation":"OutOfProcess","loadMode":"Manual","operations":["getState","ping"]}"#,
        );
        let result = discover_modules(&[root]);
        assert!(result.payload.modules[0].valid);
        assert_eq!(
            result.records["demo.operations"]
                .operations
                .iter()
                .cloned()
                .collect::<Vec<_>>(),
            vec!["getState".to_string(), "ping".to_string()]
        );
        assert!(!serde_json::to_string(&result.payload.modules[0])
            .expect("summary")
            .contains("getState"));
        let _ = fs::remove_dir_all(temp);
    }

    #[test]
    fn invalid_declared_operation_does_not_enter_the_lookup_index() {
        let (temp, root) = temp_module(
            "bad-operations",
            r#"{"id":"demo.badops","name":"Bad Operations","version":"1.0.0","entry":"entry.exe","runtimeType":"Process","runtimeIsolation":"OutOfProcess","loadMode":"Manual","operations":["../escape"]}"#,
        );
        let result = discover_modules(&[root]);
        assert!(!result.payload.modules[0].valid);
        assert!(result.payload.modules[0]
            .issues
            .iter()
            .any(|issue| issue.code == "operationInvalid"));
        assert!(result.records.is_empty());
        let _ = fs::remove_dir_all(temp);
    }

    #[test]
    fn invalid_manifest_is_reported_without_a_lookup_record() {
        let (temp, root) = temp_module(
            "broken",
            r#"{"id":"broken.test","name":"Broken","version":"1.0.0","entry":"missing.exe","runtimeType":"Process","runtimeIsolation":"OutOfProcess","loadMode":"Manual"}"#,
        );
        let result = discover_modules(&[root]);
        assert_eq!(result.payload.modules.len(), 1);
        assert!(!result.payload.modules[0].valid);
        assert!(result.records.is_empty());
        let _ = fs::remove_dir_all(temp);
    }

    #[test]
    fn legacy_manifest_is_not_treated_as_a_new_host_module() {
        let (temp, root) = temp_module(
            "legacy",
            r#"{"id":"legacy.module","name":"Legacy","version":"1.0.0","entry":"entry.exe"}"#,
        );
        let result = discover_modules(&[root]);
        let summary = &result.payload.modules[0];
        assert!(!summary.valid);
        assert!(summary
            .issues
            .iter()
            .any(|issue| issue.code == "runtimeTypeMissing"));
        assert!(result.records.is_empty());
        let _ = fs::remove_dir_all(temp);
    }
}
