[package]
name = "qing-powerguard-module"
version = "0.1.0"
edition = "2021"
rust-version = "1.77.2"
publish = false

[dependencies]
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.145"

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = "z"
panic = "abort"
strip = true
