using System.Text.Json;
using QingToolbox.Shell.Startup;
using QingToolbox.Shell.WebShell;

var root=Directory.GetCurrentDirectory();var dev=ApplicationExecutionEnvironment.Sandbox(ApplicationEnvironmentKind.Development,"WebShellSmoke",root);
Console.WriteLine("Verifying Web Shell environment and state boundary...");
Require(!new WebShellState(ApplicationExecutionEnvironment.Production()).IsEnvironmentAllowed,"Production must disable Web Shell.");Require(new WebShellState(dev).IsEnvironmentAllowed,"Development must allow Web Shell.");Require(!new WebShellState(ApplicationExecutionEnvironment.Sandbox(ApplicationEnvironmentKind.ModuleTest,"WebShellSmoke",root)).IsEnvironmentAllowed,"ModuleTest must disable Web Shell.");
var state=new WebShellState(dev);Require(!state.IsReady,"A source assignment must not imply readiness.");state.BeginInitialization();state.BeginNavigation();Require(!state.IsReady,"Navigation must not imply readiness.");state.AwaitReady();Require(!state.IsReady,"Navigation completion must await web.ready.");state.MarkReady();Require(state.IsReady,"Only the validated handshake may mark ready.");
var recovery=new WebShellState(dev);Require(recovery.TryBeginProcessRecovery()&&!recovery.TryBeginProcessRecovery(),"Only one recovery is allowed.");recovery.FallBack("WebShell.ProcessFailure.Repeated");Require(recovery.Availability==WebShellAvailability.NativeFallback,"Repeated failure must fall back.");

Console.WriteLine("Verifying navigation and network denial...");var navigation=new WebNavigationPolicy();Require(navigation.IsAllowed(WebNavigationPolicy.StartUri),"Local host must be allowed.");Require(!navigation.IsAllowed(new Uri("https://example.com"))&&!navigation.IsAllowed(new Uri("http://app.qingtoolbox.local")),"External resources must be denied.");Require(!navigation.AllowNewWindow(null)&&!navigation.AllowDownload(null)&&!navigation.AllowPermission(null),"Capabilities must be denied.");

Console.WriteLine("Verifying protocol v2, allowlist, payload and size limits...");var dispatcher=new WebBridgeDispatcher([new EchoHandler()]);var id=Guid.NewGuid().ToString();
async Task<WebBridgeDispatchResult> Send(object value)=>await dispatcher.DispatchAsync(JsonSerializer.Serialize(value));
var success=await Send(new{protocolVersion=2,requestId=id,command="app.ping",payload=new{}});Require(success.Response.Success&&success.ValidatedCommand=="app.ping","Validated command metadata is required.");
Require(!(await Send(new{protocolVersion=1,requestId=id,command="app.ping",payload=new{}})).Response.Success,"Old protocol must fail.");Require(!(await Send(new{protocolVersion=2,requestId=id,command="app.ping",payload=(object?)null})).Response.Success,"Null payload must fail.");Require(!(await Send(new{protocolVersion=2,requestId=id,command="app.ping",payload=new{danger=true}})).Response.Success,"Extra payload fields must fail.");
var disguised=await Send(new{protocolVersion=2,requestId=id,command="app.ping",payload=new{text="web.ready"}});Require(!disguised.Response.Success&&disguised.ValidatedCommand is null,"Payload text must not trigger ready.");
var huge="{\"protocolVersion\":2,\"requestId\":\""+id+"\",\"command\":\"app.ping\",\"payload\":{\"x\":\""+new string('x',WebBridgeProtocol.MaximumRequestBytes)+"\"}}";Require(!(await dispatcher.DispatchAsync(huge)).Response.Success,"Oversized request must fail.");
var unknown=await Send(new{protocolVersion=2,requestId=id,command="module.load",payload=new{path="C:\\private"}});Require(unknown.Response.Error?.Code=="UnknownCommand"&&!unknown.Response.Error.Message.Contains("C:\\"),"Errors must not disclose paths.");

Console.WriteLine("Verifying launch boundary...");var opts=ApplicationLaunchOptions.Parse(["--environment","Development","--profile","WebShellTools","--repo-root",root,"--web-devtools"]);Require(opts.EnableWebDevTools,"Development must accept explicit tools.");try{ApplicationLaunchOptions.Parse(["--environment","Production","--web-devtools"]);throw new InvalidOperationException("Production accepted tools.");}catch(ArgumentException){}
var probe=Guid.NewGuid();var probeOptions=ApplicationLaunchOptions.Parse(["--environment","Development","--profile","WebShellProbe","--repo-root",root,"--web-shell-probe",probe.ToString()]);Require(probeOptions.WebShellProbeId==probe,"Development must preserve an explicit probe identity.");try{ApplicationLaunchOptions.Parse(["--environment","Production","--web-shell-probe",probe.ToString()]);throw new InvalidOperationException("Production accepted a Web Shell probe.");}catch(ArgumentException){}
Console.WriteLine("Web Shell smoke test passed.");
static void Require(bool condition,string message){if(!condition)throw new InvalidOperationException(message);}
file sealed class EchoHandler:IWebCommandHandler{public string Command=>"app.ping";public IReadOnlySet<string> AllowedPayloadProperties{get;}=new HashSet<string>();public Task<object> HandleAsync(JsonElement payload,CancellationToken token)=>Task.FromResult<object>(new{pong=true});}
