using System.Security.Cryptography;
using System.Text.Json;
using QingToolbox.Shell.Startup;
using QingToolbox.Shell.WebShell;

var root=Directory.GetCurrentDirectory();var dev=ApplicationExecutionEnvironment.Sandbox(ApplicationEnvironmentKind.Development,"WebShellSmoke",root);
Console.WriteLine("Verifying Web Shell environment and activation boundary...");
Require(!new WebShellState(ApplicationExecutionEnvironment.Production()).IsEnvironmentAllowed,"Production must disable Web Shell.");Require(new WebShellState(dev).IsEnvironmentAllowed,"Development must allow Web Shell.");Require(!new WebShellState(ApplicationExecutionEnvironment.Sandbox(ApplicationEnvironmentKind.ModuleTest,"WebShellSmoke",root)).IsEnvironmentAllowed,"ModuleTest must disable Web Shell.");
var state=new WebShellState(dev);state.BeginInitialization();state.BeginNavigation();state.AwaitReady();Require(!state.IsReady,"Navigation and ready challenge must not activate the workspace.");
var activation=new WebActivationSession();activation.Begin(1);var nonce=activation.IssueChallenge();Require(!activation.IsActivated(1),"Challenge issuance must not activate.");Reject(()=>activation.AcceptPing(null));Reject(()=>activation.AcceptPing("wrong"));activation.AcceptPing(nonce);Require(activation.IsActivated(1),"Current challenge ping must activate.");Reject(()=>activation.AcceptPing(nonce));activation.Begin(2);Require(!activation.IsActivated(1),"Old generation activation must expire.");Reject(()=>activation.AcceptPing(nonce));var nonce2=activation.IssueChallenge();activation.AcceptPing(nonce2);Require(activation.IsActivated(2),"New generation challenge must activate.");state.MarkReady();Require(state.IsReady,"Only acknowledged activation may mark ready.");
var recovery=new WebShellState(dev);Require(recovery.TryBeginProcessRecovery()&&!recovery.TryBeginProcessRecovery(),"Only one recovered generation is allowed.");recovery.FallBack("WebShell.ProcessFailure.Repeated");Require(recovery.Availability==WebShellAvailability.NativeFallback,"A new failure after recovery must fall back.");
var failures=new WebProcessFailureGate();using var generationOne=new CancellationTokenSource();var coreOne=new object();failures.Bind(coreOne,1,generationOne.Token);Require(!failures.TryAccept(new object(),1,generationOne.Token,false),"A stale Core failure must be ignored.");Require(failures.TryAccept(coreOne,1,generationOne.Token,false),"The current generation failure must be accepted.");Require(!failures.TryAccept(coreOne,1,generationOne.Token,false),"A duplicate same-generation failure must be coalesced.");generationOne.Cancel();Require(!failures.TryAccept(coreOne,1,generationOne.Token,false),"A cancelled session failure must be ignored.");using var generationTwo=new CancellationTokenSource();var coreTwo=new object();failures.Bind(coreTwo,2,generationTwo.Token);Require(!failures.TryAccept(coreOne,1,generationOne.Token,false),"An old generation failure must remain ignored after recovery.");Require(failures.TryAccept(coreTwo,2,generationTwo.Token,false),"A real recovered-generation failure must be accepted.");Require(!failures.TryAccept(coreTwo,2,generationTwo.Token,true),"A disposed Host must ignore process failures.");
Require(!WebBridgeHost.TryPost(()=>throw new ObjectDisposedException("core")),"Posting to a disposed Core must be isolated.");Require(!WebBridgeHost.TryPost(()=>throw new System.Runtime.InteropServices.COMException()),"Posting through a failed COM Core must be isolated.");Require(WebBridgeHost.TryPost(()=>{}),"A healthy Bridge post must succeed.");

Console.WriteLine("Verifying navigation, protocol v3, allowlist and payload limits...");var navigation=new WebNavigationPolicy();Require(navigation.IsAllowed(WebNavigationPolicy.StartUri)&&!navigation.IsAllowed(new Uri("https://example.com")),"Only the local origin is allowed.");Require(!navigation.AllowNewWindow(null)&&!navigation.AllowDownload(null)&&!navigation.AllowPermission(null),"Browser capabilities must be denied.");
var dispatcher=new WebBridgeDispatcher([new EchoHandler()]);var id=Guid.NewGuid().ToString();async Task<WebBridgeDispatchResult> Send(object value)=>await dispatcher.DispatchAsync(JsonSerializer.Serialize(value));
var success=await Send(new{protocolVersion=3,requestId=id,command="app.ping",payload=new{activationNonce="test"}});Require(success.Response.Success&&success.ValidatedCommand=="app.ping","Validated command metadata is required.");
Require(!(await Send(new{protocolVersion=2,requestId=id,command="app.ping",payload=new{activationNonce="test"}})).Response.Success,"Old protocol must fail.");Require(!(await Send(new{protocolVersion=3,requestId=id,command="app.ping",payload=(object?)null})).Response.Success,"Null payload must fail.");Require(!(await Send(new{protocolVersion=3,requestId=id,command="app.ping",payload=new{danger=true}})).Response.Success,"Unexpected payload must fail.");
var huge="{\"protocolVersion\":3,\"requestId\":\""+id+"\",\"command\":\"app.ping\",\"payload\":{\"activationNonce\":\""+new string('x',WebBridgeProtocol.MaximumRequestBytes)+"\"}}";Require(!(await dispatcher.DispatchAsync(huge)).Response.Success,"Oversized request must fail.");

Console.WriteLine("Verifying host-anchored runtime assets...");var sourceAssets=Path.Combine(AppContext.BaseDirectory,"WebUI");var valid=new WebAssetIdentity(sourceAssets);Require(valid.AllowedFiles.ContainsKey("index.html")&&!valid.TryResolve("/qing-web-assets.json",out _),"Only manifested output assets may be served.");
var temp=Path.Combine(Path.GetTempPath(),"QingToolbox-WebAssetSmoke-"+Guid.NewGuid().ToString("N"));CopyTree(sourceAssets,temp);
try
{
    File.WriteAllText(Path.Combine(temp,"extra.txt"),"extra");RejectAsset(temp);File.Delete(Path.Combine(temp,"extra.txt"));
    var manifestPath=Path.Combine(temp,"qing-web-assets.json");var manifest=JsonSerializer.Deserialize<WebAssetManifest>(File.ReadAllText(manifestPath),new JsonSerializerOptions(JsonSerializerDefaults.Web))!;var target=manifest.OutputFiles[0];var targetPath=Path.Combine(temp,target.Path.Replace('/',Path.DirectorySeparatorChar));File.AppendAllText(targetPath,"tamper");var bytes=File.ReadAllBytes(targetPath);var changed=target with{Size=bytes.LongLength,Sha256=Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant()};var changedManifest=manifest with{OutputFiles=manifest.OutputFiles.Select(x=>x.Path==target.Path?changed:x).ToArray()};File.WriteAllText(manifestPath,JsonSerializer.Serialize(changedManifest,new JsonSerializerOptions(JsonSerializerDefaults.Web)));RejectAsset(temp);
}
finally{Directory.Delete(temp,true);}

Console.WriteLine("Verifying Development-only probe boundary...");var probe=Guid.NewGuid();var options=ApplicationLaunchOptions.Parse(["--environment","Development","--profile","WebShellProbe","--repo-root",root,"--web-shell-probe",probe.ToString()]);Require(options.WebShellProbeId==probe,"Development must preserve probe identity.");try{ApplicationLaunchOptions.Parse(["--environment","Production","--web-shell-probe",probe.ToString()]);throw new InvalidOperationException("Production accepted probe.");}catch(ArgumentException){}
Console.WriteLine("Web Shell smoke test passed.");

static void CopyTree(string source,string target){foreach(var directory in Directory.EnumerateDirectories(source,"*",SearchOption.AllDirectories))Directory.CreateDirectory(directory.Replace(source,target));foreach(var file in Directory.EnumerateFiles(source,"*",SearchOption.AllDirectories)){var destination=file.Replace(source,target);Directory.CreateDirectory(Path.GetDirectoryName(destination)!);File.Copy(file,destination);}}
static void RejectAsset(string path){try{_ = new WebAssetIdentity(path);throw new InvalidOperationException("Tampered asset tree was accepted.");}catch(WebAssetIdentityException){}}
static void Reject(Action action){try{action();throw new InvalidOperationException("Invalid activation was accepted.");}catch(WebBridgeValidationException){}}
static void Require(bool condition,string message){if(!condition)throw new InvalidOperationException(message);}
file sealed class EchoHandler:IWebCommandHandler{public string Command=>"app.ping";public IReadOnlySet<string> AllowedPayloadProperties{get;}=new HashSet<string>{"activationNonce"};public Task<object> HandleAsync(JsonElement payload,CancellationToken token)=>Task.FromResult<object>(new{pong=true});}
