[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$ManifestPath,[Parameter(Mandatory=$true)][string]$OutputPath)
$ErrorActionPreference='Stop';$manifestPath=[IO.Path]::GetFullPath($ManifestPath)
if(-not(Test-Path -LiteralPath $manifestPath -PathType Leaf)){throw 'Verified WebUI asset manifest is missing.'}
$manifest=Get-Content -LiteralPath $manifestPath -Raw -Encoding UTF8|ConvertFrom-Json
if($manifest.schemaVersion-ne 1-or[string]::IsNullOrWhiteSpace($manifest.assetBuildId)){throw 'WebUI asset manifest identity is invalid.'}
$hash=(Get-FileHash -LiteralPath $manifestPath -Algorithm SHA256).Hash.ToLowerInvariant();$output=[IO.Path]::GetFullPath($OutputPath);[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($output))|Out-Null
$source=@"
// <auto-generated />
namespace QingToolbox.Shell.WebShell;
internal static class WebAssetBuildInfo
{
    internal const int SchemaVersion = $([int]$manifest.schemaVersion);
    internal const string ExpectedAssetBuildId = "$([string]$manifest.assetBuildId)";
    internal const string ExpectedManifestSha256 = "$hash";
}
"@
[IO.File]::WriteAllText($output,$source.TrimStart(),[Text.UTF8Encoding]::new($false))
