<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive, ref } from 'vue'
import { invoke, onPresentationChanged, onStateChanged } from './bridge'
import type { Peer, Presentation, State } from './types'

const fallback: State = { discovery: { running: false, peers: [] }, session: { state: 'Idle', peer: null }, incomingConnection: null, incomingFile: null, receive: { defaultDirectory: null, useDefaultDirectory: false, autoAccept: false }, transfer: null, lastError: null }
const state = reactive<State>(structuredClone(fallback))
const presentation = reactive<Presentation>({ appearancePresetId: 'qing-default', languageCode: 'en-US' })
const resources = ref<Record<string, string>>({})
const busy = ref(false)
const notice = ref('')
const connected = computed(() => state.session.state === 'Connected')
const locale = computed(() => presentation.languageCode === 'zh-CN' ? 'zh-CN' : 'en-US')
const t = (key: string, fallbackText = key) => resources.value[key] ?? fallbackText
const platform = (peer: Peer) => peer.platform.toLowerCase() === 'android' ? t('platform.android', 'Android') : t('platform.windows', 'Windows')
const endpoint = (peer: Peer) => `${peer.addresses.join(', ')}:${peer.port}`
const run = async (method: string, payload?: unknown) => { busy.value = true; try { const next = await invoke<State>(method, payload); if (next) apply(next) } catch (error) { notice.value = error instanceof Error ? error.message : t('errors.request', 'The request could not be completed.') } finally { busy.value = false } }
const apply = (next: State) => { Object.assign(state, next); if (next.lastError) notice.value = next.lastError }
async function loadResources() { try { resources.value = await fetch(`../i18n/${locale.value}.json`).then(response => response.json()) } catch { resources.value = {} } }
async function initialLoad() { await loadResources(); const next = await invoke<State>('getState'); if (next) apply(next) }
function setPref(name: 'useDefaultDirectory' | 'autoAccept', value: boolean) { run('setReceivePreferences', { [name]: value }) }
function formatBytes(bytes: number) { return new Intl.NumberFormat(locale.value).format(bytes) }
onMounted(() => { const offState = onStateChanged(apply); const offPresentation = onPresentationChanged(next => { Object.assign(presentation, next); void loadResources() }); void initialLoad(); onUnmounted(() => { offState(); offPresentation() }) })
</script>

<template>
  <main class="shell" :data-theme="presentation.appearancePresetId">
    <header class="hero"><div><p class="eyebrow">QING TOOLBOX</p><h1>{{ t('view.title', 'QingTransfer') }}</h1><p>{{ t('view.subtitle', 'Discover nearby QingToolbox devices on this local network.') }}</p></div><button class="secondary" :disabled="busy" @click="run('refresh')">↻ {{ t('actions.refresh', 'Refresh') }}</button></header>
    <section v-if="connected" class="card connected"><div><span class="status-dot"></span><strong>{{ t('status.connected', 'Connected') }}</strong><p>{{ state.session.peer?.displayName }}</p></div><div class="actions"><button class="primary" :disabled="busy" @click="run('chooseAndSendFile')">{{ t('actions.sendFile', 'Send file') }}</button><button class="secondary" :disabled="busy" @click="run('disconnect')">{{ t('actions.disconnect', 'Disconnect') }}</button></div></section>
    <section class="card"><div class="card-heading"><div><h2>{{ t('view.footer', 'Nearby devices') }}</h2><p>{{ state.discovery.running ? t('status.searching', 'Looking for nearby devices...') : t('status.paused', 'Discovery paused.') }}</p></div></div><div v-if="!state.discovery.peers.length" class="empty"><div class="empty-icon">⌁</div><strong>{{ t('view.empty', 'No QingToolbox devices are online yet.') }}</strong><p>{{ t('view.hint', 'Discovery uses local DNS-SD. No connection or transfer is started here.') }}</p></div><div v-else class="peer-grid"><article v-for="peer in state.discovery.peers" :key="peer.serviceName" class="peer"><div class="peer-icon">{{ peer.platform.toLowerCase() === 'android' ? 'A' : 'W' }}</div><div class="peer-main"><h3>{{ peer.displayName }}</h3><span>{{ platform(peer) }} · {{ t('status.online', 'Online') }}</span><small>{{ endpoint(peer) }}</small></div><button v-if="state.session.state === 'Idle'" class="primary small" :disabled="busy" @click="run('connect', { serviceName: peer.serviceName })">{{ t('actions.connect', 'Connect') }}</button></article></div></section>
    <section class="card settings"><div class="card-heading"><div><h2>{{ t('receive.title', 'Receiving files') }}</h2><p>{{ t('receive.autoAcceptHint', 'Automatic acceptance is used only when the default folder is enabled, configured, and writable.') }}</p></div></div><div class="setting-row"><div><strong>{{ t('receive.useDefault', 'Use default folder') }}</strong><small>{{ state.receive.defaultDirectory || t('receive.noDirectory', 'No default folder configured') }}</small></div><div class="row-actions"><button class="secondary small" @click="run('chooseReceiveDirectory')">{{ t('actions.choose', 'Choose') }}</button><button v-if="state.receive.defaultDirectory" class="ghost" @click="run('clearReceiveDirectory')">{{ t('actions.clear', 'Clear') }}</button><input type="checkbox" :checked="state.receive.useDefaultDirectory" @change="setPref('useDefaultDirectory', ($event.target as HTMLInputElement).checked)" /></div></div><div class="setting-row"><div><strong>{{ t('receive.autoAccept', 'Automatically accept files') }}</strong><small>{{ state.receive.useDefaultDirectory && state.receive.defaultDirectory ? t('receive.autoAcceptHint', 'Automatic acceptance is enabled when the folder is writable.') : t('receive.noDirectory', 'Configure a default folder first.') }}</small></div><input type="checkbox" :checked="state.receive.autoAccept" @change="setPref('autoAccept', ($event.target as HTMLInputElement).checked)" /></div></section>
    <section v-if="state.transfer" class="card progress"><div class="card-heading"><h2>{{ t('status.transfer', 'Transferring') }}</h2><span>{{ formatBytes(state.transfer.completed) }} / {{ formatBytes(state.transfer.total) }}</span></div><progress :value="state.transfer.completed" :max="Math.max(state.transfer.total, 1)"></progress><p>{{ state.transfer.name }}</p></section>
    <div v-if="state.incomingConnection" class="modal-backdrop"><div class="modal"><h2>{{ t('status.incoming', 'Incoming request from {0}').replace('{0}', state.incomingConnection.name) }}</h2><div class="actions"><button class="primary" @click="run('acceptIncomingConnection')">{{ t('actions.accept', 'Accept') }}</button><button class="secondary" @click="run('rejectIncomingConnection')">{{ t('actions.reject', 'Reject') }}</button></div></div></div>
    <div v-if="state.incomingFile" class="modal-backdrop"><div class="modal"><h2>{{ t('receive.incoming', 'Incoming file') }}</h2><p>{{ state.incomingFile.name }} · {{ t('receive.fileSize', '{0} bytes').replace('{0}', formatBytes(state.incomingFile.size)) }}</p><p>{{ t('receive.incomingHint', 'Choose where to save this file.') }}</p><div class="actions"><button class="primary" @click="run('acceptIncomingFile')">{{ t('actions.choose', 'Choose') }}</button><button class="secondary" @click="run('rejectIncomingFile')">{{ t('actions.reject', 'Reject') }}</button></div></div></div>
    <div v-if="notice" class="notice" @click="notice = ''">{{ notice }}</div>
  </main>
</template>
