package com.qingtoolbox.android

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.Color as AndroidColor
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.Clear
import androidx.compose.material.icons.outlined.QrCode2
import androidx.compose.material.icons.outlined.Share
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.OutlinedTextFieldDefaults
import androidx.compose.material3.SnackbarHost
import androidx.compose.material3.SnackbarHostState
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.core.content.FileProvider
import kotlinx.coroutines.launch
import java.io.File

@Composable
fun QrCodeScreen(modifier: Modifier = Modifier) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    val snackbarHostState = remember { SnackbarHostState() }
    val style = LocalQingAppearance.current
    val scheme = MaterialTheme.colorScheme
    val fieldShape = androidx.compose.foundation.shape.RoundedCornerShape(style.controlCornerRadius)
    val fieldColors = OutlinedTextFieldDefaults.colors(
        focusedBorderColor = scheme.primary,
        unfocusedBorderColor = style.controlBorderColor,
        focusedLabelColor = scheme.primary,
        unfocusedLabelColor = scheme.onSurfaceVariant,
        cursorColor = scheme.primary,
        errorBorderColor = scheme.error,
        errorCursorColor = scheme.error,
        errorLabelColor = scheme.error,
    )
    var input by rememberSaveable { mutableStateOf("") }
    var generated by remember { mutableStateOf<Bitmap?>(null) }
    var errorMessage by rememberSaveable { mutableStateOf<String?>(null) }

    fun generate() {
        try {
            val matrix = QrCodeEncoder.encode(input)
            generated = QrBitmapRenderer.render(matrix)
            errorMessage = null
        } catch (_: Exception) {
            generated = null
            errorMessage = "Could not generate a QR code for this text."
        }
    }

    fun clear() {
        input = ""
        generated = null
        errorMessage = null
    }

    Box(modifier = modifier.fillMaxSize()) {
        LazyColumn(
            modifier = Modifier.fillMaxSize(),
            contentPadding = PaddingValues(horizontal = 20.dp, vertical = 16.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp),
        ) {
            item {
                QingCard(modifier = Modifier.fillMaxWidth()) {
                    Column(
                        modifier = Modifier.padding(18.dp),
                        verticalArrangement = Arrangement.spacedBy(10.dp),
                    ) {
                        Row(
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(12.dp),
                        ) {
                            QingIconSurface(modifier = Modifier.size(44.dp)) {
                                Icon(
                                    imageVector = Icons.Outlined.QrCode2,
                                    contentDescription = null,
                                    tint = scheme.primary,
                                )
                            }
                            Column {
                                Text(
                                    text = "QR Code",
                                    style = MaterialTheme.typography.titleMedium,
                                    fontWeight = FontWeight.SemiBold,
                                )
                                Text(
                                    text = "Generate a black-and-white QR code from text.",
                                    style = MaterialTheme.typography.bodySmall,
                                    color = scheme.onSurfaceVariant,
                                )
                            }
                        }
                        OutlinedTextField(
                            value = input,
                            onValueChange = {
                                input = it
                                generated = null
                                errorMessage = null
                            },
                            modifier = Modifier
                                .fillMaxWidth()
                                .height(156.dp),
                            label = { Text("Text") },
                            placeholder = { Text("Enter text, URL, or multiple lines") },
                            minLines = 6,
                            maxLines = 6,
                            isError = errorMessage != null,
                            shape = fieldShape,
                            colors = fieldColors,
                        )
                        Text(
                            text = "${input.length} characters",
                            style = MaterialTheme.typography.labelSmall,
                            color = scheme.onSurfaceVariant,
                        )
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.spacedBy(10.dp),
                        ) {
                            QingPrimaryButton(
                                onClick = ::generate,
                                enabled = input.isNotBlank(),
                                modifier = Modifier.weight(1f),
                            ) {
                                Icon(Icons.Outlined.QrCode2, contentDescription = null)
                                Spacer(Modifier.size(8.dp))
                                Text("Generate")
                            }
                            QingSecondaryButton(
                                onClick = ::clear,
                                modifier = Modifier.weight(1f),
                            ) {
                                Icon(Icons.Outlined.Clear, contentDescription = null)
                                Spacer(Modifier.size(8.dp))
                                Text("Clear")
                            }
                        }
                    }
                }
            }
            if (errorMessage != null) {
                item {
                    QingCard(modifier = Modifier.fillMaxWidth()) {
                        Text(
                            text = errorMessage.orEmpty(),
                            color = scheme.error,
                            style = MaterialTheme.typography.bodyMedium,
                            modifier = Modifier.padding(18.dp),
                        )
                    }
                }
            }
            if (generated != null) {
                item {
                    QingCard(modifier = Modifier.fillMaxWidth()) {
                        Column(
                            modifier = Modifier.padding(16.dp),
                            verticalArrangement = Arrangement.spacedBy(12.dp),
                        ) {
                            Text(
                                text = "Preview",
                                style = MaterialTheme.typography.titleMedium,
                                fontWeight = FontWeight.SemiBold,
                            )
                            Box(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .aspectRatio(1f)
                                    .background(androidx.compose.ui.graphics.Color.White),
                                contentAlignment = Alignment.Center,
                            ) {
                                Image(
                                    bitmap = generated!!.asImageBitmap(),
                                    contentDescription = "Generated QR code",
                                    modifier = Modifier.fillMaxSize(),
                                )
                            }
                            QingSecondaryButton(
                                onClick = {
                                    val bitmap = generated ?: return@QingSecondaryButton
                                    shareQrCode(context, bitmap) { message ->
                                        scope.launch { snackbarHostState.showSnackbar(message) }
                                    }
                                },
                                modifier = Modifier.fillMaxWidth(),
                            ) {
                                Icon(Icons.Outlined.Share, contentDescription = null)
                                Spacer(Modifier.size(8.dp))
                                Text("Share QR Code")
                            }
                        }
                    }
                }
            }
            if (generated == null && errorMessage == null) {
                item {
                    QingStatusText(
                        text = "Generate a QR code to preview it here. The preview stays black and white for reliable reading.",
                        modifier = Modifier.padding(top = 4.dp, bottom = 20.dp),
                    )
                }
            } else {
                item {
                    QingStatusText(
                        text = "QR images are staged in app cache only when you choose Share.",
                        modifier = Modifier.padding(top = 4.dp, bottom = 20.dp),
                    )
                }
            }
        }
        SnackbarHost(
            hostState = snackbarHostState,
            modifier = Modifier
                .align(Alignment.BottomCenter)
                .padding(16.dp),
        )
    }
}

private object QrBitmapRenderer {
    fun render(matrix: QrMatrix): Bitmap {
        val pixels = IntArray(matrix.size * matrix.size) { index ->
            if (matrix.isDark(index % matrix.size, index / matrix.size)) AndroidColor.BLACK else AndroidColor.WHITE
        }
        return Bitmap.createBitmap(matrix.size, matrix.size, Bitmap.Config.ARGB_8888).also {
            it.setPixels(pixels, 0, matrix.size, 0, 0, matrix.size, matrix.size)
        }
    }
}

private fun shareQrCode(context: Context, bitmap: Bitmap, onMessage: (String) -> Unit) {
    try {
        val shareDirectory = File(context.cacheDir, "qr-share")
        if (!shareDirectory.exists() && !shareDirectory.mkdirs()) {
            onMessage("Could not prepare the QR code for sharing.")
            return
        }
        val output = File(shareDirectory, "qrcode.png")
        output.outputStream().use { stream ->
            check(bitmap.compress(Bitmap.CompressFormat.PNG, 100, stream))
        }
        val uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            output,
        )
        val shareIntent = Intent(Intent.ACTION_SEND).apply {
            type = "image/png"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(shareIntent, "Share QR Code"))
    } catch (_: Exception) {
        onMessage("Could not share the QR code.")
    }
}
